<?php
// Version: 2.0; ManageMedia

$txt['embed_enabled'] = '<strong>Activer l\'intégration automatique (YouTube, etc.)</strong>';
$txt['embed_enabled_desc'] = 'Outrepasse tout';
$txt['embed_lookups'] = 'Autoriser les lookups (vérifications distantes)';
$txt['embed_lookup_success'] = 'Votre serveur supporte les lookups.';
$txt['embed_lookup_fail'] = 'Votre serveur ne supporte PAS les lookups.';
$txt['embed_max_per_post'] = 'Nombre maximal d\'intégrations par message';
$txt['embed_max_per_page'] = 'Nombre maximal d\'intégrations par page';
$txt['embed_max_warning'] = 'Attention, l\'abus de Flash peut nuire à la santé de votre navigateur !';
$txt['embed_quotes'] = 'Autoriser l\'intégration dans les citations (quotes)';
$txt['embed_mov'] = '.MOV (via Quicktime)';
$txt['embed_real'] = '.RAM/.RM (via Real Media)';
$txt['embed_wmp'] = '.WMV/.WMA (via Windows Media)';
$txt['embed_swf'] = '.SWF (Animations en Flash)';
$txt['embed_flv'] = '.FLV (Vidéos en Flash)';
$txt['embed_divx'] = '.DIVX (via lecteur DivX)';
$txt['embed_avi'] = '.AVI (via lecteur DivX)';
$txt['embed_mp3'] = '.MP3 (via lecteur Flash)';
$txt['embed_mp4'] = '.MP4 (via lecteur Flash)';
$txt['embed_ext'] = 'Extensions de fichier autorisées';
$txt['embed_fix_html'] = 'Corriger quand un lien HTML d\'intégration (embed link) est utilisé à la place de l\'URL';
$txt['embed_includeurl'] = 'Inclure le lien d\'origine';
$txt['embed_includeurl_desc'] = '(pour les sites qui ne l\'indiquent pas dans leur lecteur)';
$txt['embed_local'] = 'Intégrer les fichiers locaux (sauf fichiers joints)';
$txt['embed_local_desc'] = 'Locaux signifie qu\'ils sont sur le même serveur. Mais cela n\'autorise pas pour autant l\'intégration de n\'importe quel fichier de ce type n\'importe où.';
$txt['embed_denotes'] = '(Les sites annotés d\'un * nécessitent un lookup)';
$txt['embed_fish'] = '(Les sites annotés d\'un * nécessitent un lookup, mais cette fonctionnalité n\'est pas supportée par votre serveur.<br>À moins de rechercher l\'URL intégrable manuellement, vous ne pourrez pas intégrer de vidéos de ces sites.)';
$txt['embed_pop_sites'] = 'Sites Populaires';
$txt['embed_video_sites'] = 'Sites Vidéo';
$txt['embed_audio_sites'] = 'Sites Audio';
$txt['embed_other_sites'] = 'Autres Sites';
$txt['embed_adult_sites'] = 'Sites pour Adultes';
$txt['embed_custom_sites'] = 'Sites Personnels';
$txt['embed_disable'] = 'Désactiver l\'intégration';
$txt['embed_titles'] = 'Stocker et montrer les titres des vidéos';
$txt['embed_titles_desc'] = '(si le site est supporté par Wedge)';
$txt['embed_titles_yes'] = 'Oui, stocker et montrer';
$txt['embed_titles_yes2'] = 'Oui, mais suspendre le stockage';
$txt['embed_titles_no'] = 'Non, mais continuer à stocker pour plus tard';
$txt['embed_titles_no2'] = 'Non, ne rien montrer, ne rien stocker';
$txt['embed_inlinetitles'] = 'Montrer les titres dans les vignettes';
$txt['embed_inlinetitles_desc'] = '(pour les sites le proposant, comme YouTube et Vimeo)';
$txt['embed_inlinetitles_yes'] = 'Oui';
$txt['embed_inlinetitles_maybe'] = 'Seulement si le titre n\'est pas stocké';
$txt['embed_inlinetitles_no'] = 'Non';
$txt['embed_noscript'] = 'Éviter d\'utiliser JavaScript pour l\'intégration';
$txt['embed_noscript_desc'] = 'Uniquement si vous avez des soucis de compatibilité...';
$txt['embed_expins'] = 'Utiliser la mise à jour express de Flash';
$txt['embed_expins_desc'] = 'Si la version Flash de l\'utilisateur est périmée, un utilitaire de mise à jour automatique s\'affichera';
$txt['embed_lookups_desc'] = 'La plupart des fonctionnalités nécessitent un lookup.';
$txt['embed_center'] = 'Centrer toutes les vidéos horizontalement';
$txt['embed_center_desc'] = 'Ou ajoutez "-center" aux options de la vidéo (exemple&#8239;: #ws-hd-center)';
$txt['embed_lookup_titles'] = 'Toujours essayer de chercher les titres';
$txt['embed_lookup_titles_desc'] = '(même sur les sites non supportés, donc...)';
$txt['embed_incontext'] = 'Autoriser l\'intégration dans les phrases';
$txt['embed_nonlocal'] = 'Accepter les sites externes en plus des adresses internes';
$txt['embed_nonlocal_desc'] = 'Au cas où vous ne l\'auriez pas déjà compris, c\'est fortement déconseillé, du moins en matière de sécurité.';
$txt['embed_max_width'] = 'Largeur maximale pour les vidéos intégrées';
$txt['embed_max_width_desc'] = 'Laissez vide pour désactiver. Entrez 600 pour une largeur maximale de 600 pixels. Les vidéos plus larges seront redimensionnées, et celles plus petites afficheront un lien permettant de les élargir.';
$txt['embed_yq'] = 'Qualité YouTube par défaut';
$txt['embed_yq_default'] = 'Défaut';
$txt['embed_yq_hd'] = 'HD si disponible';
$txt['embed_small'] = 'Normal';
$txt['embed_large'] = 'Large';

$txt['media_admin_settings_title_main'] = 'Réglages principaux';
$txt['media_admin_settings_title_security'] = 'Réglages de sécurité';
$txt['media_admin_settings_title_limits'] = 'Limites';
$txt['media_admin_settings_title_tag'] = 'Tag [media] et intégration';
$txt['media_admin_settings_title_misc'] = 'Divers';
$txt['media_admin_settings_welcome'] = 'Message d\'accueil';
$txt['media_admin_settings_welcome_desc'] = 'Laissez vide pour utiliser le message d\'accueil par défaut.';
$txt['media_admin_settings_data_dir_path'] = 'Chemin vers le répertoire de données';
$txt['media_admin_settings_data_dir_path_desc'] = 'Chemin sur le serveur (exemple&#8239;: /home/www/media)';
$txt['media_admin_settings_data_dir_url'] = 'Adresse du répertoire de données';
$txt['media_admin_settings_data_dir_url_desc'] = 'Même chemin, mais accessible par le web (exemple&#8239;: http://mysite.com/media)';
$txt['media_admin_settings_max_dir_files'] = 'Nombre maximal de fichiers par répertoire';
$txt['media_admin_settings_enable_re-rating'] = 'Autoriser à changer son vote';
$txt['media_admin_settings_use_metadata_date'] = 'Utiliser la date Exif si possible';
$txt['media_admin_settings_use_metadata_date_desc'] = 'Si le fichier contient des données Exif, la date de publication affichée sera celle donnée par Exif au lieu de l\'heure actuelle.';
$txt['media_admin_settings_title_files'] = 'Réglages pour les fichiers';
$txt['media_admin_settings_title_previews'] = 'Réglages pour les prévisualisations';
$txt['media_admin_settings_max_file_size'] = 'Taille maximale des fichiers';
$txt['media_admin_settings_max_file_size_desc'] = 'Mettez à 0 et utilisez la section Quotas pour affiner.';
$txt['media_admin_settings_max_width'] = 'Largeur maximale';
$txt['media_admin_settings_max_height'] = 'Hauteur maximale';
$txt['media_admin_settings_allow_over_max'] = 'Autoriser le redimensionnement';
$txt['media_admin_settings_allow_over_max_desc'] = 'Si l\'image envoyée dépasse les dimensions autorisées, le serveur tentera de la redimensionner à la taille maximale autorisée. À éviter pour les serveurs surchargés. Choisissez &quot;Non&quot; pour rejeter l\'image.';
$txt['media_admin_settings_upload_security_check'] = 'Activer la sécurité pendant l\'envoi de fichiers';
$txt['media_admin_settings_upload_security_check_desc'] = 'Permet d\'empêcher l\'envoi de fichiers malicieux, mais peut parfois rejeter des fichiers sains. Inutile de l\'activer, sauf si vous avez des utilisateurs d\'IE vraiment, mais vraiment idiots, et qui cherchent les ennuis.';
$txt['media_admin_settings_log_access_errors'] = 'Archiver les erreurs d\'accès';
$txt['media_admin_settings_log_access_errors_desc'] = 'Si activé, toutes les erreurs d\'accès refusé dans la section Media seront archivées dans le journal d\'erreurs.';
$txt['media_admin_settings_ftp_file'] = 'Chemin d\'accès du fichier Safe Mode';
$txt['media_admin_settings_ftp_file_desc'] = 'Lisez le fichier MGallerySafeMode.php pour plus d\'informations. Nécessaire si votre serveur est en Safe Mode !';
$txt['media_admin_settings_jpeg_compression'] = 'Compression Jpeg';
$txt['media_admin_settings_jpeg_compression_desc'] = 'Qualité des images redimensionnées (dont les aperçus et les vignettes), de 0 (fichiers légers, mauvaise qualité) à 100 (gros fichiers, haute qualité). La valeur par défaut (80) est recommandée. Restez entre 65 et 85.';
$txt['media_admin_settings_show_extra_info'] = 'Afficher les métadonnées';
$txt['media_admin_settings_show_info'] = 'Métadonnées à montrer';
$txt['media_admin_settings_show_info_desc'] = 'Les images prises par des appareils numériques renferment souvent des informations utiles, telles que l\'heure où a été pris un cliché. Vous pouvez choisir de les montrer ou pas.';
$txt['media_admin_settings_num_items_per_page'] = 'Nombre d\'éléments par page';
$txt['media_admin_settings_max_thumbs_per_page'] = 'Tags [media] max par page';
$txt['media_admin_settings_max_thumbs_per_page_desc'] = 'Nombre maximal de tags [media] autorisés par page (ceux-ci sont transformés en vignettes)';
$txt['media_admin_settings_recent_item_limit'] = 'Derniers éléments à montrer';
$txt['media_admin_settings_random_item_limit'] = 'Éléments au hasard à montrer';
$txt['media_admin_settings_recent_comments_limit'] = 'Derniers commentaires à montrer';
$txt['media_admin_settings_recent_albums_limit'] = 'Derniers albums à montrer';
$txt['media_admin_settings_max_thumb_width'] = 'Largeur maximale pour la vignette';
$txt['media_admin_settings_max_thumb_height'] = 'Hauteur maximale pour la vignette';
$txt['media_admin_settings_max_preview_width'] = 'Largeur maximale pour l\'aperçu';
$txt['media_admin_settings_max_preview_width_desc'] = 'L\'aperçu est une image intermédiaire cliquable qui est montrée sur la fiche consacrée à l\'image en taille réelle. Mettez à 0 pour désactiver sa génération. <b>Attention</b>, si les aperçus sont désactivés, les images de grande taille déformeront peut-être l\'apparence de vos pages.';
$txt['media_admin_settings_max_preview_height'] = 'Hauteur maximale pour l\'aperçu';
$txt['media_admin_settings_max_preview_height_desc'] = 'Même chose. Si la largeur ou la hauteur est à 0, la génération d\'aperçus est désactivée.';
$txt['media_admin_settings_max_bigicon_width'] = 'Largeur maximale pour l\'icône';
$txt['media_admin_settings_max_bigicon_width_desc'] = 'Les icônes d\'album ont une vignette (dont la taille est la même que pour les vignettes d\'éléments), ainsi qu\'une icône de taille arbitraire, montrée uniquement sur les pages des albums. Vous pouvez régler ici la largeur maximale de cette icône.';
$txt['media_admin_settings_max_bigicon_height'] = 'Hauteur maximale pour l\'icône';
$txt['media_admin_settings_max_bigicon_height_desc'] = 'Même chose. Vous pouvez régler ici la hauteur maximale de cette icône.';
$txt['media_admin_settings_max_title_length'] = 'Longueur maximale des titres';
$txt['media_admin_settings_max_title_length_desc'] = 'Nombre maximal de caractères à afficher pour les titres au-dessus des vignettes. Si coupés, ils restent lisibles en passant la souris sur la vignette.';
$txt['media_admin_settings_enable_cache'] = 'Activer le cache';
$txt['media_admin_settings_image_handler'] = 'Gestionnaire d\'images';
$txt['media_admin_settings_show_sub_albums_on_index'] = 'Montrer les sous-albums dans l\'index';
$txt['media_admin_settings_use_zoom'] = 'Utiliser Zoomedia (transitions animées)';
$txt['media_admin_settings_use_zoom_desc'] = 'Zoomedia est un module JavaScript qui ajoute des transitions animées en cliquant sur les aperçus (zoom et fondu enchaîné). Désactivez pour empêcher l\'utilisation de Zoomedia sur tous les albums. Si activé, les propriétaires d\'albums pourront tout de même désactiver Zoomedia sur leurs albums via leurs réglages par album.';
$txt['media_admin_settings_album_edit_unapprove'] = 'Nécessiter une réapprobation après modification sur un album';
$txt['media_admin_settings_item_edit_unapprove'] = 'Nécessiter une réapprobation après modification sur un élément';
$txt['media_admin_settings_show_linking_code'] = 'Afficher le code pour lier vers les images';
$txt['media_admin_settings_ffmpeg_installed'] = 'FFMPEG a été trouvé sur ce serveur, ses fonctions peuvent être utilisées pour les fichiers vidéo. S\'il est activé, il sera utilisé pour créer des vignettes et pour montrer des informations supplémentaires.';
$txt['media_admin_settings_prev_next'] = 'Montrer les éléments précédents et suivants&#8239;?';
$txt['media_admin_settings_prev_next_desc'] = 'Activez cette option pour montrer sur les pages d\'éléments des raccourcis (image ou texte) vers les éléments précédents et suivants.';
$txt['media_admin_settings_default_tag_type'] = 'Taille par défaut dans les tags [media]&#8239;?';
$txt['media_admin_settings_default_tag_type_desc'] = 'Choisissez le type d\'image à afficher par défaut quand aucun type n\'est spécifié pour les images affichées via le tag [media id=xxx type=xxx]';
$txt['media_admin_settings_my_docs'] = 'Documents autorisés';
$txt['media_admin_settings_my_docs_desc'] = 'Vous pouvez choisir la liste des extensions autorisées pour les Documents envoyés. Séparez-les par des virgules (ex: "zip,pdf"). Si vous voulez remettre la liste à zéro, voici les extensions supportées par défaut&#8239;: %s';
$txt['media_admin_settings_player_color'] = 'Couleur du lecteur audio/vidéo';
$txt['media_admin_settings_player_color_desc'] = 'En code héxa. Par défaut, blanc (FFFFFF)';
$txt['media_admin_settings_player_bcolor'] = 'Couleur de fond du lecteur audio/vidéo';
$txt['media_admin_settings_player_bcolor_desc'] = 'En code héxa. Par défaut, noir (000000)';
$txt['media_admin_settings_audio_player_width'] = 'Largeur du lecteur audio';
$txt['media_admin_settings_audio_player_width_desc'] = 'En pixels. Par défaut, 400';
$txt['media_admin_settings_phpini_desc'] = 'Cette variable serveur limite la taille des envois, elle est configurée via le fichier php.ini (voir documentation à droite)';
$txt['media_admin_settings_clear_thumbnames'] = 'Laisser en clair les adresses des vignettes';
$txt['media_admin_settings_clear_thumbnames_desc'] = 'Si activé, les vignettes seront liées directement par leur URL. Gain de temps mais confidentialité amoindrie.';
$txt['media_admin_settings_album_columns'] = 'Nombre de sous-albums par ligne';
$txt['media_admin_settings_album_columns_desc'] = 'Par défaut, 1. Si vous avez beaucoup de sous-albums, n\'hésitez pas à mettre 2 ou 3 colonnes pour avoir plus d\'albums par ligne.';
$txt['media_admin_settings_icons_only'] = 'Utiliser les icônes comme raccourcis';
$txt['media_admin_settings_icons_only_desc'] = 'Si cette option est activée, seules les icônes seront montrées sous les vignettes des boîtes d\'éléments, comme par exemple les listes d\'éléments sur les pages d\'albums. <em>Par</em>, <em>Visites</em>, etc. seront cachés pour gagner en place.';
$txt['media_admin_settings_disable_playlists'] = 'Désactiver les playlists utilisateur';
$txt['media_admin_settings_disable_playlists_desc'] = 'Désactive la fonctionnalité des listes de lecture des utilisateurs.';
$txt['media_admin_settings_disable_comments'] = 'Désactiver les commentaires';
$txt['media_admin_settings_disable_comments_desc'] = 'Cache les commentaires existants et empêche d\'en poster de nouveaux.';
$txt['media_admin_settings_disable_ratings'] = 'Désactiver les notes';
$txt['media_admin_settings_disable_ratings_desc'] = 'Cache les notes existantes et empêche de noter les éléments.';

$txt['media_admin_moderation'] = 'Modération';
$txt['media_admin_moving_album'] = 'Déplacer un album';
$txt['media_admin_cancel_moving'] = 'Annuler le déplacement';
$txt['media_admin_type'] = 'Type';
$txt['media_admin_edit'] = 'Modifier';
$txt['media_admin_delete'] = 'Effacer';
$txt['media_admin_approve'] = 'Approuver';
$txt['media_admin_unapprove'] = 'Désapprouver';
$txt['media_admin_before'] = 'Avant';
$txt['media_admin_after'] = 'Après';
$txt['media_admin_child_of'] = 'Enfant de';
$txt['media_admin_target'] = 'Cible';
$txt['media_admin_position'] = 'Position';
$txt['media_admin_membergroups'] = 'Groupes de membres';
$txt['media_admin_membergroups_desc'] = 'Choisissez les groupes de membres qui seront autorisés à accéder à l\'album et à son contenu.<br>
<ul class="aevadesc">
	<li>Si les <strong>groupes primaires</strong> (indiqués en gras) sont cochés, tous les membres du forum pourront accéder à l\'album, il est donc inutile de cocher les autres groupes (sauf Invités).</li>
	<li>Accès en <strong>Lecture</strong> : le groupe peut consulter l\'album et ses éléments, et utiliser les éventuelles permissions accordées (commenter, noter, etc.)</li>
	<li>Accès en <strong>Écriture</strong> : le groupe peut contribuer à l\'album en y envoyant des éléments.</li>
</ul>';
$txt['media_admin_membergroups_primary'] = 'Ce groupe est utilisé comme groupe primaire par un ou plusieurs membres.';
$txt['media_admin_passwd'] = 'Mot de passe';
$txt['media_admin_move'] = 'Déplacer';
$txt['media_admin_total_submissions'] = 'Nombre de soumissions';
$txt['media_maintenance_done'] = 'Maintenance effectuée';
$txt['media_pruning'] = 'Nettoyage';
$txt['media_admin_maintenance_prune_days'] = ' jours au-delà desquels l\'élément est considéré comme ancien';
$txt['media_admin_maintenance_prune_last_comment_age'] = 'Dernier commentaire plus vieux que';
$txt['media_admin_maintenance_prune_max_coms'] = 'Nombre de commentaires inférieur à';
$txt['media_admin_maintenance_prune_max_views'] = 'Nombre de visites inférieur à';
$txt['media_admin_maintenance_checkfiles_desc'] = 'Cherche les fichiers superflus (introuvables dans la table media_items), et offre la possibilité de les supprimer.';
$txt['media_admin_maintenance_checkorphans'] = 'Éliminer les fichiers orphelins';
$txt['media_admin_maintenance_checkorphans_desc'] = 'Cherche les fichiers orphelins (introuvables dans la table media_files), et offre la possibilité de les supprimer. <strong>Attention !</strong> Si vous lancez cette opération, votre galerie sera <strong>inutilisable</strong> tant que ses trois phases ne seront pas terminées. Le processus peut prendre beaucoup de temps sur une galerie conséquente.';
$txt['media_admin_maintenance_regen_all'] = 'Régénérer les vignettes et aperçus';
$txt['media_admin_maintenance_regen_embed'] = 'Régénérer les vignettes des éléments intégrés';
$txt['media_admin_maintenance_regen_thumb'] = 'Régénérer les vignettes';
$txt['media_admin_maintenance_regen_preview'] = 'Régénérer les aperçus';
$txt['media_admin_maintenance_regen_all_desc'] = 'Cette fonction supprimera et recréera tous les aperçus et vignettes existants, mais seulement s\'ils peuvent être recréés à partir de leur fichier source.';
$txt['media_admin_maintenance_regen_embed_desc'] = 'Cette fonction supprimera et recréera les vignettes, mais uniquement pour les <b>éléments intégrés</b> (YouTube ou autres).';
$txt['media_admin_maintenance_regen_thumb_desc'] = 'Cette fonction supprimera et recréera toutes les vignettes existantes, mais uniquement si elles peuvent être recréées à partir du fichier source ou de l\'aperçu.';
$txt['media_admin_maintenance_regen_preview_desc'] = 'Cette fonction supprimera et recréera tous les aperçus existants, mais uniquement s\'ils peuvent être recréés à partir du fichier source.';
$txt['media_admin_maintenance_operation_pending'] = 'L\'opération a été interrompue pour éviter de surcharger le serveur. Elle reprendra automatiquement dans une seconde. %s éléments terminés sur %s.';
$txt['media_admin_maintenance_operation_pending_raw'] = 'L\'opération a été interrompue pour éviter de surcharger le serveur. Elle reprendra automatiquement dans une seconde.';
$txt['media_admin_maintenance_operation_phase'] = 'Phase %d/%d';
$txt['media_admin_maintenance_recount_desc'] = 'Recompte les totaux et les statistiques et les met à jour. Peut être utilisé pour réparer des statistiques incorrectes.';
$txt['media_admin_maintenance_finderrors_desc'] = 'Cherche les erreurs telles que fichier manquant (physique ou dans la base de données), ou ID de dernier message ou d\'élément incorrect.';
$txt['media_admin_maintenance_prune_desc'] = 'Utilitaire pour purger les commentaires/éléments avec des paramètres spécifiques';
$txt['media_admin_maintenance_browse_desc'] = 'Utilitaire pour parcourir les fichiers, montre aussi l\'utilisation d\'espace d\'un dossier/fichier';
$txt['media_admin_labels_modlog'] = 'Journal';
$txt['media_admin_action_type'] = 'Type d\'action';
$txt['media_admin_reported_item'] = 'Élément signalé';
$txt['media_admin_reported_by'] = 'Signalé par';
$txt['media_admin_reported_on'] = 'Signalé le';
$txt['media_admin_del_report'] = 'Supprimer le rapport';
$txt['media_admin_del_report_item'] = 'Supprimer l\'élément signalé';
$txt['media_admin_report_reason'] = 'Raison du signalement';
$txt['media_admin_banned_on'] = 'Banni le';
$txt['media_admin_expires_on'] = 'Expire le';
$txt['media_never'] = 'Jamais';
$txt['media_admin_ban_type'] = 'Type de bannissement';
$txt['media_admin_ban_type_1'] = 'Complet';
$txt['media_admin_ban_type_2'] = 'Ajout d\'éléments';
$txt['media_admin_ban_type_3'] = 'Ajout de commentaires';
$txt['media_admin_ban_type_4'] = 'Ajout d\'éléments et de commentaires';
$txt['media_unapproved_items_notice'] = 'Il y a %2$d élément(s) non approuvé(s). <a href="%1$s">Cliquez ici pour les voir</a>.';
$txt['media_unapproved_coms_notice'] = 'Il y a %2$d commentaire(s) non approuvé(s). <a href="%1$s">Cliquez ici pour les voir</a>.';
$txt['media_unapproved_albums_notice'] = 'Il y a %2$d album(s) non approuvé(s). <a href="%1$s">Cliquez ici pour les voir</a>.';
$txt['media_reported_items_notice'] = '%2$d élément(s) ont été signalés. <a href="%1$s">Cliquez ici pour les voir</a>';
$txt['media_reported_comments_notice'] = '%2$d commentaire(s) ont été signalés. <a href="%1$s">Cliquez ici pour les voir</a>';
$txt['media_admin_modlog_approval_item'] = 'Approuvé l\'élément <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_ua_item'] = 'Désapprouvé l\'élément <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_item'] = 'Supprimé l\'élément %s (était en attente d\'approbation)';
$txt['media_admin_modlog_approval_com'] = 'Approuvé le commentaire <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_com'] = 'Supprimé un commentaire de l\'élément %s (était en attente d\'approbation)';
$txt['media_admin_modlog_approval_album'] = 'Approuvé l\'album <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_album'] = 'Supprimé l\'album %s (était en attente d\'approbation)';
$txt['media_admin_modlog_delete_item'] = 'Supprimé l\'élément %s';
$txt['media_admin_modlog_delete_album'] = 'Supprimé l\'album %s';
$txt['media_admin_modlog_delete_comment'] = 'Supprimé un commentaire de l\'élément %s';
$txt['media_admin_modlog_delete_report_item_report'] = 'Supprimé une plainte concernant l\'élément #%s';
$txt['media_admin_modlog_delete_report_comment_report'] = 'Supprimé une plainte concernant le commentaire #%s';
$txt['media_admin_modlog_delete_item_item_report'] = 'Supprimé l\'élément signalé #%s';
$txt['media_admin_modlog_delete_item_comment_report'] = 'Supprimé le commentaire signalé #%s';
$txt['media_admin_modlog_ban_add'] = 'Banni <a href="%s">%s</a>';
$txt['media_admin_modlog_ban_delete'] = 'Débanni <a href="%s">%s</a>';
$txt['media_admin_modlog_prune_item'] = 'Purgé %s élément(s)';
$txt['media_admin_modlog_prune_comment'] = 'Purgé %s commentaire(s)';
$txt['media_admin_modlog_move'] = 'Déplacé <a href=%s">%s</a> de l\'album <a href="%s">%s</a> vers <a href="%s">%s</a>';
$txt['media_admin_modlog_qsearch'] = 'Recherche rapide par membre';
$txt['media_admin_modlog_filter'] = 'Journal de modération filtré par <a href="%s">%s</a>';
$txt['media_admin_view_image'] = 'Voir l\'image';
$txt['media_admin_ftp_files'] = 'Fichiers dans le dossier FTP';
$txt['media_admin_profile_add'] = 'Créer un profil';
$txt['media_admin_prof_name'] = 'Nom du profil';
$txt['media_admin_create_prof'] = 'Créer le profil';
$txt['media_admin_members'] = 'Membres';
$txt['media_admin_prof_del_switch'] = 'Passer les albums à ce profil';
$txt['media_quota_profile'] = 'Profil de quotas';
$txt['media_album_hidden'] = 'Désactiver la navigation';
$txt['media_album_hidden_desc'] = 'Activez cette option pour empêcher la navigation dans l\'album à tout le monde sauf vous. Ses éléments RESTERONT visionnables aux groupes autorisés. Utile pour faire un album dont les éléments ne doivent être publiés que sur des messages de forum.';
$txt['media_allowed_members'] = 'Membres autorisés (lecture)';
$txt['media_allowed_members_desc'] = 'Entrez un par un les noms des membres dont vous souhaitez qu\'ils puissent consulter l\'album, même si leurs groupes n\'y sont pas autorisés.';
$txt['media_allowed_write'] = 'Membres autorisés (écriture)';
$txt['media_allowed_write_desc'] = 'Entrez un par un les noms des membres dont vous souhaitez qu\'ils puissent envoyer des éléments dans l\'album, même si leurs groupes n\'y sont pas autorisés.';
$txt['media_denied_members'] = 'Membres bannis (lecture)';
$txt['media_denied_members_desc'] = 'Entrez un par un les noms des membres à qui vous souhaitez refuser de consulter l\'album, même si leurs groupes y sont autorisés.';
$txt['media_denied_write'] = 'Membres bannis (écriture)';
$txt['media_denied_write_desc'] = 'Entrez un par un les noms des membres à qui vous souhaitez refuser d\'envoyer des éléments dans l\'album, même si leurs groupes y sont autorisés.';
$txt['media_admin_wselected'] = 'Avec la sélection';
$txt['media_admin_select_or'] = 'Ou...';
$txt['media_admin_apply_perm'] = 'Ajouter permission';
$txt['media_admin_clear_perm'] = 'Effacer permission';
$txt['media_admin_set_mg_perms'] = 'Utiliser les permissions de ce groupe';

// Admin error strings
$txt['media_admin_album_confirm'] = 'Êtes-vous sûr de vouloir supprimer cet album ? Cela supprimera aussi les éléments et les commentaires inclus.';
$txt['media_admin_name_left_empty'] = 'Le nom n\'a pas été entré';
$txt['media_admin_invalid_target'] = 'Cible spécifiée invalide';
$txt['media_admin_invalid_position'] = 'Position spécifiée invalide';
$txt['media_admin_prune_invalid_days'] = 'Données &quot;jours&quot; non valides';
$txt['media_admin_no_albums'] = 'Pas d\'album spécifié';
$txt['media_admin_rm_selected'] = 'Supprimer la sélection';
$txt['media_admin_rm_all'] = 'Tout supprimer';
$txt['media_report_not_found'] = 'Signalement introuvable';
$txt['media_admin_bans_mems_empty'] = 'Aucun membre n\'a été spécifié';
$txt['media_admin_bans_mems_not_found'] = 'Les membres spécifiés sont introuvables';
$txt['media_ban_not_found'] = 'Bannissement introuvable';
$txt['media_admin_already_banned'] = 'Utilisateur déjà banni';
$txt['media_admin_unique_permission'] = 'Vous devez ne sélectionner qu\'une option';
$txt['media_admin_quick_none'] = 'Pas d\'option sélectionnée';
$txt['media_admin_invalid_groups'] = 'Une sélection invalide a été détectée. Peut-être le groupe sélectionné n\'existe-t-il pas. Si vous copiez des permissions, assurez-vous d\'avoir sélectionné au moins un groupe, et de ne pas y avoir mis le groupe dont vous copiez les permissions.';

// Admin help strings
$txt['media_admin_desc'] = 'Administration Media';
$txt['media_admin_settings_desc'] = 'Vous êtes sur la page générale de configuration de la section Media.';
$txt['media_admin_embed_desc'] = 'Vous êtes sur la page de configuration de l\'intégration automatique de medias. Vous pouvez y activer ou désactiver l\'intégration des liens multimédia provenant de sites tels que YouTube. Vous pouvez également consulter la liste des sites supportés, et les activer séparément.';
$txt['media_admin_albums_desc'] = 'Vous êtes sur la page d\'administration des albums. Vous pouvez y gérer l\'ajout, la suppression, la modification et le déplacement d\'albums. En cliquant sur le bouton <strong>+</strong>, vous obtiendrez plus d\'informations au sujet d\'un album.';
$txt['media_admin_subs_desc'] = 'Vous êtes sur la page d\'administration des soumissions, vous pouvez y voir/supprimer/approuver les éléments/commentaires/albums en attente d\'approbation.';
$txt['media_admin_maintenance_desc'] = 'Vous êtes sur la page de maintenance, vous y trouverez de nombreuses tâches et fonctions utiles pour votre installation.';
$txt['media_admin_modlog_desc'] = 'Vous êtes sur la page du journal de modération de la section Media, vous y trouverez les activités de modération qui s\'y rapportent.';
$txt['media_admin_reports_desc'] = 'Vous êtes sur la page d\'administration des signalements. Vous pouvez y consulter/supprimer les éléments/commentaires signalés par des utilisateurs, ou supprimer des rapports de signalement.';
$txt['media_admin_bans_desc'] = 'Vous êtes sur la page d\'administration des bannissements de la section Media. Vous pouvez y gérer les utilisateurs bannis. Votre toute-puissance n\'a d\'égale que votre cruauté, maître.';
$txt['media_admin_about_desc'] = 'Bienvenue dans la zone d\'administration de la section Media !';
$txt['media_admin_passwd_desc'] = 'Pour réserver l\'accès à cet album à ceux qui en ont le mot de passe. Sinon, laissez vide.';
$txt['media_admin_maintenance_finderror_pending'] = 'Ce script est toujours actif. %s éléments sur %s sont terminés pour le moment.<br><br>Veuillez <a href="%s">cliquer ici</a> pour continuer. Assurez-vous d\'avoir attendu 1 à 2 secondes afin d\'éviter les surcharges.';
$txt['media_admin_finderrors_1'] = 'Les erreurs suivantes ont été trouvées par la recherche d\'erreurs';
$txt['media_admin_finderrors_missing_db_file'] = 'L\'entrée de base de données du fichier %s, utilisée pour l\'élément <a href="%s">%s</a>, est manquante.';
$txt['media_admin_finderrors_missing_db_thumb'] ='L\'entrée de base de données de la vignette %s, utilisée pour l\'élément <a href="%s">%s</a>, est manquante.';
$txt['media_admin_finderrors_missing_db_preview'] ='L\'entrée de base de données de l\'aperçu %s, utilisé pour l\'élément <a href="%s">%s</a>, est manquante.';
$txt['media_admin_finderrors_missing_physical_file'] = 'Le fichier %s, utilisé par l\'élément <a href="%s">%s</a>, est manquant.';
$txt['media_admin_finderrors_missing_physical_thumb'] = 'Le fichier de la vignette %s, associée à l\'élément <a href="%s">%s</a>, est manquant.';
$txt['media_admin_finderrors_missing_physical_preview'] = 'Le fichier de l\'aperçu %s, associé à l\'élément <a href="%s">%s</a>, est manquant.';
$txt['media_admin_finderrors_missing_album'] = 'L\'album %s, associé à l\'élément <a href="%s">%s</a>, est manquant.';
$txt['media_admin_finderrors_missing_last_comment'] = 'Le commentaire %s, associé à l\'élément <a href="%s">%s</a> en tant que dernier commentaire, est manquant.';
$txt['media_admin_finderrors_parent_album_access'] = 'L\'album %s a été mis à jour pour retirer les groupes n\'ayant pas accès à son album parent.';
$txt['media_admin_finderrors_done'] = 'Vérification des erreurs terminée. Aucune erreur trouvée&#8239;!';
$txt['media_admin_prune_done_items'] = 'Nettoyage des éléments terminé&#8239;! %s élément(s), %s commentaire(s) et %s fichier(s) supprimé(s)';
$txt['media_admin_prune_done_comments'] = 'Nettoyage des commentaires terminé&#8239;! %s commentaire(s) supprimé(s)';
$txt['media_admin_maintenance_prune_item_help'] = 'Pour le nettoyage des éléments, vous pouvez supprimer les éléments qui ont plus de &quot;x&quot; jours, x pouvant être défini ci-dessous. Il y a quelques options supplémentaires <b>mais sont optionnelles</b>. Les albums peuvent être sélectionnés ensemble ou individuellement.';
$txt['media_admin_maintenance_prune_com_help'] = 'Pour le nettoyage des commentaires, vous pouvez nettoyer les commentaires qui ont plus de &quot;x&quot; jours dans tous les albums, ou dans un album spécifié.';
$txt['media_admin_maintenance_checkfiles_done'] = 'Les fichiers inutiles ont tous été supprimés, pour un total de %s fichiers, libérant %s ko d\'espace disque.';
$txt['media_admin_maintenance_checkfiles_no_files'] = 'Pas de fichiers superflus trouvés';
$txt['media_admin_maintenance_checkfiles_found'] = '%s fichier(s) superflu(s) trouvé(s), consommant %s ko d\'espace supplémentaire. <a href="%s">Cliquez ici</a> pour le(s) supprimer.';
$txt['media_admin_maintenance_checkorphans_done'] = 'Les fichiers orphelins suivants ont été supprimés, pour un total de %s fichiers&#8239;:';
$txt['media_admin_maintenance_checkorphans_no_files'] = 'Pas de fichiers orphelins trouvés';
$txt['media_admin_maintenance_clear_pending'] = 'Ce script est toujours actif. %s éléments sur %s sont terminés pour le moment.<br><br>Veuillez <a href="%s">cliquer ici</a> pour continuer. Assurez-vous d\'avoir attendu 1 à 2 secondes afin d\'éviter les surcharges.';
$txt['media_admin_maintenance_clear_done'] = 'Tous les fichiers ont été renommés avec succès.';
$txt['media_admin_installed_on'] = 'Installé le';
$txt['media_admin_icon_edit_desc'] = 'Si vous désirez envoyer une icône, l\'ancienne sera écrasée. Laissez vide pour conserver l\'ancienne.';
$txt['media_admin_bans_mems_empty'] = 'Aucun membre n\'a été spécifié';
$txt['media_admin_expires_on_help'] = 'Doit être indiqué en &quot;jours&quot;, à partir de maintenant';
$txt['media_admin_modlog_desc'] = 'Le journal de modération vous propose la liste de toutes les actions de modération effectuées sur la galerie. N\'oubliez pas qu\'une fois effacées, les données du journal ne sont plus récupérables.';
$txt['media_admin_ftp_desc'] = 'Cette section vous permet d\'importer des éléments vers la galerie via un dossier distant sur le serveur. Cela permet notamment de mettre en place des fichiers plus gros que ne l\'autoriserait PHP pour un envoi classique.';
$txt['media_admin_ftp_help'] = 'Voici la liste des fichiers dans le dossier {Data_dir}/ftp. Merci de choisir l\'album de destination pour chaque dossier.';
$txt['media_admin_ftp_halted'] = 'Importation mise en pause pour éviter une surcharge serveur, %s importés sur %s. Le processus va reprendre automatiquement.';
$txt['media_admin_perms_desc'] = 'Cette section vous permet de gérer les différents profils de permissions, destinés à gérer les autorisations sur les albums.';
$txt['media_admin_prof_del_switch_help'] = 'Si vous désirez supprimer un profil utilisé par un ou plusieurs albums, vous devrez attribuer un autre profil aux albums en question.';
$txt['media_admin_quotas_desc'] = 'D\'ici, vous pouvez gérer les profils de quotas des groupes de membres. Oui, ça fait peur rien qu\'à le prononcer, ça.';
$txt['media_admin_perms_warning'] = '<strong>Attention</strong>, les permissions générales d\'accès à la section Media sont à régler, groupe de membre par groupe de membre, dans <a href="%s">l\'administration classique</a>.';

// Per-album Permissions
$txt['permissionname_media_download_item'] = 'Télécharger des éléments';
$txt['permissionname_media_add_videos'] = 'Ajouter des fichiers vidéo';
$txt['permissionname_media_add_audios'] = 'Ajouter des fichiers audio';
$txt['permissionname_media_add_docs'] = 'Ajouter des documents';
$txt['permissionname_media_add_embeds'] = 'Ajouter des fichiers intégrés';
$txt['permissionname_media_add_images'] = 'Ajouter des images';
$txt['permissionname_media_rate_items'] = 'Donner des notes aux éléments';
$txt['permissionname_media_edit_own_com'] = 'Modifier ses commentaires';
$txt['permissionname_media_report_com'] = 'Signaler des commentaires';
$txt['permissionname_media_edit_own_item'] = 'Modifier ses éléments';
$txt['permissionname_media_comment'] = 'Commenter des éléments';
$txt['permissionname_media_report_item'] = 'Signaler des éléments';
$txt['permissionname_media_auto_approve_com'] = 'Auto-approuver ses commentaires';
$txt['permissionname_media_auto_approve_item'] = 'Auto-approuver ses uploads';
$txt['permissionname_media_multi_upload'] = 'Envoyer des fichiers en masse';
$txt['permissionname_media_whoratedwhat'] = 'Voir qui a voté quoi';
$txt['permissionname_media_multi_download'] = 'Télécharger des albums zippés';

// Custom fields
$txt['media_cf_invalid'] = 'Valeur invalide pour %s';
$txt['media_cf_empty'] = 'Le champ %s a été laissé vide';
$txt['media_cf_bbc'] = 'Ce champ peut utiliser du BBCode';
$txt['media_cf_required'] = 'Ce champ est requis';
$txt['media_cf_desc'] = 'D\'ici vous pouvez gérer les champs personnels';
$txt['media_admin_labels_fields'] = 'Champs personnels';
$txt['media_cf_name'] = 'Nom du champ';
$txt['media_cf_type'] = 'Type de champ';
$txt['media_cf_req'] = 'Requis';
$txt['media_cf_searchable'] = 'Recherchable';
$txt['media_cf_bbcode'] = 'BBC';
$txt['media_cf_editing'] = 'Ajouter/modifier un champ personnel';
$txt['media_cf_text'] = 'Texte';
$txt['media_cf_radio'] = 'Boutons radio';
$txt['media_cf_checkbox'] = 'Cases à cocher';
$txt['media_cf_textbox'] = 'Champ texte';
$txt['media_cf_select'] = 'Liste déroulante';
$txt['media_cf_options'] = 'Options du champ';
$txt['media_cf_options_desc'] = 'Ajouter des options pour les champs - valable uniquement pour les types Cases à cocher, Liste déroulante ou Boutons radio. Séparez les choix par des virgules (,)';
