<?php
// Version: 2.0; Errors

$txt['cannot_access_mod_center'] = 'You do not have permission to access the moderation centre.';

$txt['not_removed_extra'] = '%1$s is a backup of %2$s that was not generated by Wedge. It can be accessed directly and used to gain unauthorised access to your forum. You should delete it immediately.';
