<?php
// Version: 2.0; ManageMaintenance

$txt['repair_zero_ids'] = 'İleti veya Konu ID\'si 0 olan iletiler ve konular bulundu.';
$txt['repair_missing_topics'] = 'İleti #%1$d  var olmayan #%2$d konusuna aittir.';
$txt['repair_missing_messages'] = 'Konu #%1$d herhangi bir ileti bulundurmamaktadır.';
$txt['repair_stats_topics_1'] = 'Konu #%1$d doğru olmayan %2$d ilk ileti ID\'sine sahiptir.';
$txt['repair_stats_topics_2'] = 'Konu %1$d doğru olmayan %2$d son ileti ID\'sine sahiptir.';
$txt['repair_stats_topics_3'] = 'Konu %1$d doğru olmayan %2$d ileti sayısına sahiptir.';
$txt['repair_stats_topics_4'] = 'Konu %1$d doğru olmayan %2$d onaylanmamış ileti sayısına sahiptir.';
$txt['repair_stats_topics_5'] = 'Konu %1$d doğru olmayan onay işaretine sahiptir.';
$txt['repair_missing_boards'] = 'Konu %1$d varolmayan %2$d bölümüne aittir.';
$txt['repair_missing_categories'] = 'Bölüm %1$d varolmayan %2$d kategorisine aittir.';
$txt['repair_missing_posters'] = 'İleti %1$d varolmayan üye %2$d tarafından gönderilmiştir.';
$txt['repair_missing_parents'] = 'Bölüm #%1$d varolmayan #%2$d bölümünün bir alt bölümüdür.';
$txt['repair_missing_polls'] = 'Konu #%1$d varolmayan #%2$d anketi ile ilişkilendirilmiştir.';
$txt['repair_polls_missing_topics'] = '#%1$d , anket olmayan bir konuya bağlanmış #%2$d.';
$txt['repair_missing_log_topics'] = 'Varolmayan konu #%1$d birden çok kişi için okunmuş olarak işaretlidir.';
$txt['repair_missing_log_topics_members'] = 'Varolmayan üye #%1$d birden çok iletiyi okunmuş olarak işaretlemiştir.';
$txt['repair_missing_log_mark_read'] = 'Varolmayan bölüm #%1$d birden çok kişi için okunmuş olarak işaretlidir.';
$txt['repair_missing_log_mark_read_members'] = 'Varolmayan üye #%1$d birden çok bölümü okunmuş olarak işaretlemiştir.';
$txt['repair_missing_pms'] = 'Varolmayan kişisel ileti #%1$d birden çok kişiye gönderilmiştir.';
$txt['repair_missing_recipients'] = 'Varolmayan üye #%1$d birden çok kişisel ileti almıştır.';
$txt['repair_missing_senders'] = 'Varolmayan kişisel ileti #%1$d varolmayan üye #%2$d tarafından gönderilmiştir.';
$txt['repair_missing_notify_members'] = 'Varolmayan üye #%1$d, tarafından istenen haberdar edilmeler bulunmaktadır.';
$txt['repair_missing_cached_subject'] = '#%1$d konusunun başlığı başlık önbelleğinde kayıtlı değildir.';
$txt['repair_missing_topic_for_cache'] = 'Önbellekte bulunan \'%1$s\' kelimesi varolmayan bir konuya bağlıdır.';
$txt['repair_missing_log_poll_member'] = '#%1$d anketine varolmayan #%2$d üyesi tarafından oy verilmiştir.';
$txt['repair_missing_log_poll_vote'] = '#%1$d üyesi tarafından varolmayan #%2$d anketine oy verilmiştir.';
$txt['repair_missing_thumbnail_parent'] = 'Ana resmi var olmayan %1$s başlıklı bir küçük resim bulunmuştur.';
$txt['repair_report_missing_comments'] = '#%1$d konusuna ait rapora ait yorum bulunmamaktadır.';
$txt['repair_comments_missing_report'] = '#%1$d rapor yorumu, %2$s tarafından gönderilmiştir ve ait olduğu rapor yoktur.';
$txt['repair_group_request_missing_member'] = 'Silinmiş üye #%1$d için halen bir grup isteği bulunmaktadır.';
$txt['repair_group_request_missing_group'] = 'Silinmiş grup #%1$d için halen bir grup isteği bulunmaktadır..';

$txt['repair_currently_checking'] = 'Kontrol Ediliyor: &quot;%1$s&quot;';
$txt['repair_currently_fixing'] = 'Tamir Ediliyor: &quot;%1$s&quot;';
$txt['repair_operation_zero_topics'] = 'Alanı (id_topic) 0 olarak ayarlanmış konular';
$txt['repair_operation_zero_messages'] = 'Alanı (id_topic) 0 olarak ayarlanmış iletiler';
$txt['repair_operation_missing_topics'] = 'Konu girdisi kayıp iletileri';
$txt['repair_operation_missing_messages'] = 'İletisi olmayan konular';
$txt['repair_operation_stats_topics'] = 'Yanlış ilk veya son iletisi kaydına sahip konular';
$txt['repair_operation_stats_topics2'] = 'Yanlış yanıt sayısına sahip konular';
$txt['repair_operation_stats_topics3'] = 'Yanlış onaylanmamış ileti sayısına sahip konular';
$txt['repair_operation_missing_boards'] = 'Varolmayan bölümlerdeki konular';
$txt['repair_operation_missing_categories'] = 'Varolmayan kategorilerdeki bölümler';
$txt['repair_operation_missing_posters'] = 'Varolmayan üyelere bağlı iletiler';
$txt['repair_operation_missing_parents'] = 'Varolmayan bölümlere bağlı alt bölümler';
$txt['repair_operation_missing_polls'] = 'Varolmayan anketlere bağlı konular';
$txt['repair_operation_missing_log_topics'] = 'Varolmayan konulara bağlı konu kayıtları';
$txt['repair_operation_missing_log_topics_members'] = 'Varolmayan üyelere bağlı konu kayıtları';
$txt['repair_operation_missing_log_mark_read'] = 'Varolmayan bölümlere bağlı okunmuş say verisi';
$txt['repair_operation_missing_log_mark_read_members'] = 'Varolmayan üyelere bağlı okunmuş say verisi';
$txt['repair_operation_missing_pms'] = 'Ana iletisi kayıp Kişisel İleti alıcıları';
$txt['repair_operation_missing_recipients'] = 'Silinmiş üyelere gönderilmiş kişisel iletiler';
$txt['repair_operation_missing_senders'] = 'Varolmayan üyelere bağlı kişisel iletiler';
$txt['repair_operation_missing_notify_members'] = 'Varolmayan üyelere bağlı haberdar edilme kayıtları';
$txt['repair_operation_missing_cached_subject'] = 'Arama önbelleği verisi kayıp konular';
$txt['repair_operation_missing_topic_for_cache'] = 'Varolmayan konulara bağlı arama önbellek verisi';
$txt['repair_operation_missing_member_vote'] = 'Varolmayan üyelere bağlı anket oyları';
$txt['repair_operation_missing_log_poll_vote'] = 'Varolmayan anketlere bağlı anket oyları';
$txt['repair_operation_report_missing_comments'] = 'Yorumu olmayan konu raporları';
$txt['repair_operation_comments_missing_report'] = 'Konu raporları olmayan rapor yorumları';
$txt['repair_operation_group_request_missing_member'] = 'Talepte bulunan üyesi kayıp üye grupları';
$txt['repair_operation_group_request_missing_group'] = 'Varolmayan gruplar için üyelik talepleri';

$txt['salvaged_category_name'] = 'Kurtarma Alanı';
$txt['salvaged_category_error'] = 'Kurtarma Alanı kategorisi oluşturulamadı!';
$txt['salvaged_board_name'] = 'Kurtarılan Konular';
$txt['salvaged_board_description'] = 'Konusu var olmayan iletiler için oluşturulmuş kurtarma konuları';
$txt['salvaged_board_error'] = 'Kurtarılmış Konular bölümü oluşturulamadı!';
$txt['salvaged_poll_topic_name'] = 'Kurtarılmış Anket';
$txt['salvaged_poll_message_body'] = 'Bu anketin konusu bulunmuyor.';

$txt['database_optimize'] = 'Veritabanını İyileştir';
$txt['database_numb_tables'] = 'Veritabanınızda %1$d tablo bulunmaktadır.';
$txt['database_optimize_attempt'] = 'Veritabanınız iyileştirilmeye çalışılıyor...';
$txt['database_optimizing'] = '%1$s İyileştiriliyor... %2$01.2f kb iyileştirildi.';
$txt['database_optimized'] = array(0 => 'Tüm tablolar önceden optimize edilmiştir.', 1 => '%1$d tablo iyileştirildi.', 'n' => '%1$d tablo iyileştirildi.');
$txt['database_no_id'] = 'varolmayan üye ID\'sine sahip';

// Error and intrusion logs.
$txt['apply_filter'] = 'Apply Filter';
$txt['applying_filter'] = 'Applying Filter';
$txt['filter_only_member'] = 'Only show the error messages of this member';
$txt['filter_only_ip'] = 'Only show the error messages of this IP address';
$txt['filter_only_url'] = 'Only show the error messages of this URL';
$txt['filter_only_message'] = 'Only show the errors with the same message';
$txt['filter_only_ua'] = 'Only show the errors from this user agent';
$txt['error_url'] = 'Hataya yol açan sayfanın adresi';
$txt['error_message'] = 'Hata iletisi';
$txt['clear_filter'] = 'Filtre oluştur';
$txt['remove_selection'] = 'Seçilileri Kaldır';
$txt['remove_filtered_results'] = 'Tüm Filtrelenmiş Sonuçları kaldır';
$txt['sure_about_errorlog_remove'] = 'Tüm hata iletilerini kaldırmak istediğinizden emin misiniz?';
$txt['reverse_direction'] = 'Listenin kronolojik sıralamasını ters çevir';
$txt['error_type'] = 'Hata türü';
$txt['filter_only_type'] = 'Sadece bu türdeki hataları göster';
$txt['filter_only_file'] = 'Sadece bu dosyaya ait hataları göster';
$txt['apply_filter_of_type'] = 'Bu filtreyi uygula';
$txt['request_method'] = 'Request method';
$txt['request_protocol'] = 'Request protocol';
$txt['user_agent'] = 'User agent';
$txt['http_headers'] = 'Other HTTP headers:';
$txt['file_out_of_bounds'] = 'This file is shorter than the specified line number, thus it can\'t be shown. Maybe you modified it?';

$txt['errortype_all'] = 'Tüm hatalar';
$txt['errortype_general'] = 'Genel';
$txt['errortype_general_desc'] = 'Bir tür içersine kategorize edilmemiş genel hatalar';
$txt['errortype_critical'] = '<span style="color:red;">Kritik</span>';
$txt['errortype_critical_desc'] = 'Kritik hatalar. Bu hatalar olabildiğince çabuk çözülmelidirler.  Bu hataların görmezden görülmesi forumunuzun çökmesine veya forum güvenliğinin tehlikeye girmesine sebep olabilir.';
$txt['errortype_database'] = 'Veritabanı';
$txt['errortype_database_desc'] = 'Bozuk sorgular yüzünden oluşan veritabanı hataları. Bu hatalar Wedge ekibine iletilmelidir.';
$txt['errortype_undefined_vars'] = 'Tanımlanmamış';
$txt['errortype_undefined_vars_desc'] = 'Tanımlanmamış değişkenlerin kullanımından kaynaklanan hatalar.';
$txt['errortype_mail'] = 'Eposta';
$txt['errortype_mail_desc'] = 'Errors occurring while sending email. Many errors from mail may indicate faulty configuration.';
$txt['errortype_filenotfound'] = 'File not found';
$txt['errortype_filenotfound_desc'] = 'Errors caused by files being requested but not actually present on your server.';
$txt['errortype_template'] = 'Template';
$txt['errortype_template_desc'] = 'Errors related to the loading of templates.';
$txt['errortype_password'] = 'Passwords';
$txt['errortype_password_desc'] = 'Users who have entered an incorrect password.';
$txt['errortype_user'] = 'User';
$txt['errortype_user_desc'] = 'Errors resulting from user errors. Includes trying to login when banned, and trying to do an action for which they do not have permission.';

$txt['maintain_recount'] = 'Tüm Forum Toplamlarını ve İstatistiklerini Tekrar Hesapla';
$txt['maintain_recount_info'] = 'Olası bir \'ileti sayım\' veya \'toplam kişisel ileti sayım\' hatasında : bu fonksiyon sizin için kaydedilmiş sayı ve istatistikleri tekrar sayar';
$txt['maintain_errors'] = 'Hataları bul ve varsa düzelt';
$txt['maintain_errors_info'] = 'Örneğin, eğer server hataları sonucunda bazı iletiler ve konular eksilmişse , bu fonksiyon bulunmasına yardım edecektir';
$txt['maintain_logs'] = 'Gereksiz Kayıtları Temizle';
$txt['maintain_logs_info'] = 'Bu fonksiyon gereksiz logları temizliyecek. Bir sorun olmadıkça bu işlemden kaçınılmalıdır, fakat her hangi bir şeye zarar vermez';
$txt['maintain_cache'] = 'Dosya Önbelleğini Temizle';
$txt['maintain_cache_info'] = 'Ne sebeple olursa olsun, eğer ara belleğin temizlenmesi gerekiyorsa, bu link tam aradığınız işlevi gösterir.';
$txt['maintain_optimize'] = 'Tüm tabloları iyileştir';
$txt['maintain_optimize_info'] = 'Bu görev tüm tabloları en uygun hale getirmenizi sağlar. Efektleri ; Ek yüklerden kurtularak , tabloların boyutların küçülerek forumun hızlanmasını sağlar.';
$txt['maintain_version'] = 'Dosyaları Güncel Sürümleriyle Karşılaştır';
$txt['maintain_version_info'] = 'Bu bakım görevi size forum dosyalarınızın sürümü hakkında detaylı bilgi verecek ve resmi sitedeki liste ile karşılaştıracaktır ';
$txt['maintain_run_now'] = 'Görevi Çalıştır';
$txt['maintain_return'] = 'Forum Bakımına Geri Dön';

$txt['maintain_old'] = 'Eski İletileri Temizle';
$txt['maintain_old_since'] = 'Remove all topics not posted in for %1$s days, which are:';
$txt['maintain_old_move_since'] = 'Move all topics not posted in for %1$s days, which are:';
$txt['maintain_old_nothing_else'] = 'Herhangi bir konu.';
$txt['maintain_old_are_moved'] = 'Taşınma bilgilendirme konuları.';
$txt['maintain_old_are_locked'] = 'Kilitli konular.';
$txt['maintain_old_are_not_pinned'] = 'Sabit konuları sayma.';
$txt['maintain_old_all'] = 'Tüm Bölümler (belirli bölümleri seçmek için tıkla)';
$txt['maintain_old_choose'] = 'Belli Bölümleri Seç (tümünü seçmek için tıkla)';
$txt['maintain_old_remove'] = 'Kaldır';
$txt['maintain_old_confirm'] = 'Eski iletileri temizlemek istediğinizden emin misiniz?\\n\\nBu işlem geri alınamaz!';

$txt['maintain_members'] = 'Aktif Olmayan Üyeleri Temizle';
$txt['maintain_members_ungrouped'] = 'Gruplandırılmamış Üyeler <span class="smalltext">(Herhangi bir üye grubuna dahil olmayan üyeler)</span>';
$txt['maintain_members_since1'] = '';
$txt['maintain_members_since2'] = ' şu tarihten eski';
$txt['maintain_members_since3'] = ' tüm üyeleri temizle.';
$txt['maintain_members_activated'] = 'Üyeliklerini aktifleştirmemiş';
$txt['maintain_members_logged_in'] = 'Giriş yapmamış';
$txt['maintain_members_all'] = 'Tüm Üye Grupları';
$txt['maintain_members_choose'] = 'Seçili Üye Grupları';
$txt['maintain_members_confirm'] = 'Aktif olmayan üyeleri temizlemek istediğinizden emin misiniz?<br><br>Bu işlem geri alınamaz!';

$txt['maintain_recountposts'] = 'Recount Member Posts';
$txt['maintain_recountposts_desc'] = 'This will recalculate the post counts of all members within the forum, and ensure that the current count is the correct one, as well as ensuring post-count permissions are reapplied.';

// Move topics out.
$txt['move_topics_maintenance'] = 'Konuları Taşı';
$txt['move_topics_select_board'] = 'Bölüm Seç';
$txt['move_topics_from'] = 'Taşıma İşlemi:';
$txt['move_topics_to'] = '->';
$txt['move_topics_now'] = 'Şimdi Taşı';
$txt['move_topics_confirm'] = '&quot;%board_from%&quot; bölümündeki TÜM konuları &quot;%board_to%&quot; bölümüne taşımak istediğinize emin misiniz?';

$txt['maintain_reattribute_posts'] = 'Kullanıcı İletilerini İlişkilendir';
$txt['reattribute_guest_posts'] = 'Şu şekilde gönderilmiş ziyaretçi iletilerini';
$txt['reattribute_email'] = 'E-Posta';
$txt['reattribute_username'] = 'Kullanıcı Adı';
$txt['reattribute_user'] = 'Or merge from this user:';
$txt['reattribute_current_member'] = 'Üye ile ilişkilendir';
$txt['reattribute_increase_posts'] = 'İleti sayısını güncelle';
$txt['reattribute'] = 'İlişkilendir';
$txt['reattribute_confirm'] = '"%find%" (%type%) tarafından gönderilmiş tüm iletileri "%member_to%" üyesiyle ilişkilendirmek istediğinize emin misiniz?';
$txt['reattribute_confirm_merge'] = 'Are you sure you want to merge the account "%find%" with member "%member_to%"?';
$txt['reattribute_confirm_username'] = 'kullanıcı adı';
$txt['reattribute_confirm_email'] = 'e-posta adresi';
$txt['reattribute_cannot_find_member'] = 'İlişkilendirilecek üye bulunamadı.';
$txt['reattribute_cannot_find_member_from'] = 'Could not find member to merge from.';
