<?php
// Version: 2.0; ManageMedia

$txt['embed_enabled'] = '<strong>Automatischen Einbetten aktivieren</strong>';
$txt['embed_enabled_desc'] = 'Grundeinstellung';
$txt['embed_lookups'] = 'Suche nach Hostnamen aktivieren';
$txt['embed_lookup_success'] = 'Diese Funktion ist auf deinem Server verfügbar';
$txt['embed_lookup_fail'] = 'Diese Funktion ist auf deinem Server NICHT verfügbar';
$txt['embed_max_per_post'] = 'Max Einbettungen pro Beitrag';
$txt['embed_max_per_page'] = 'Max Einbettungen pro Seite';
$txt['embed_max_warning'] = 'Zu viel Flash ist schlecht für deinen Browser';
$txt['embed_quotes'] = 'Aktiviere das Einbetten in Zitaten';
$txt['embed_mov'] = 'MOV Dateien (via Quicktime)';
$txt['embed_real'] = 'RAM/RM Dateien (via Real Media)';
$txt['embed_wmp'] = 'WMV/WMA Dateien (via Windows Media)';
$txt['embed_swf'] = 'SWF Flash Animationen';
$txt['embed_flv'] = 'FLV Flash-Videos';
$txt['embed_divx'] = 'DivX Dateien (.divx)';
$txt['embed_avi'] = 'AVI Dateien (via DivX Player)';
$txt['embed_mp3'] = 'MP3 Dateien (via Flash Player)';
$txt['embed_mp4'] = 'MP4 Dateien (via Flash Player)';
$txt['embed_ext'] = 'Erlaubte Dateierweiterungen';
$txt['embed_fix_html'] = 'Repariert die HTML-Ausgabe von einem eingebetteten Link';
$txt['embed_includeurl'] = 'Original-Link einbinden';
$txt['embed_includeurl_desc'] = '(für Seiten, die diese Funktion nicht im Player haben)';
$txt['embed_local'] = 'Lokale Dateien einbetten [schließt Dateianhänge aus]';
$txt['embed_local_desc'] = 'Lokal bedeutet, dass die Datei auf dem selben Server liegt.';
$txt['embed_denotes'] = '(Seiten die mit * markiert sind benötigen Lookups)';
$txt['embed_fish'] = '(Seiten die mit einem * markiert sind benötigen Lookups. Lookups sind von deinem Server aus NICHT möglich.<br>Einbetten wird für diese Seiten nicht funktionieren.)';
$txt['embed_pop_sites'] = 'Beliebte Seiten';
$txt['embed_video_sites'] = 'Video-Seiten';
$txt['embed_audio_sites'] = 'Audio-Seiten';
$txt['embed_other_sites'] = 'Andere Seiten';
$txt['embed_adult_sites'] = 'Seiten für Erwachsene';
$txt['embed_custom_sites'] = 'Benutzerdefinierte Seiten';
$txt['embed_disable'] = 'Einbetten deaktivieren';
$txt['embed_titles'] = 'Speichern und Videotitel anzeigen';
$txt['embed_titles_desc'] = '(falls diese Seite von Wedge unterstützt wird)';
$txt['embed_titles_yes'] = 'Ja, Lookup und anzeigen';
$txt['embed_titles_yes2'] = 'Ja, aber nichts Neues abspeichern';
$txt['embed_titles_no'] = 'Nein, aber für später vormerken';
$txt['embed_titles_no2'] = 'Nein, nicht speichern und nicht anzeigen';
$txt['embed_inlinetitles'] = 'Titel innerhalb der Vorschaubilder anzeigen';
$txt['embed_inlinetitles_desc'] = '(für unterstütze Seiten wie YouTube und Vimeo)';
$txt['embed_inlinetitles_yes'] = 'Ja';
$txt['embed_inlinetitles_maybe'] = 'Nur wenn der Titel nicht bereits gespeichert ist';
$txt['embed_inlinetitles_no'] = 'Nein';
$txt['embed_noscript'] = 'Verwende ein früheres System zur Einbettung mit weniger JavaScript';
$txt['embed_noscript_desc'] = 'Nur verwenden wenn Kompatibilitätsprobleme auftauchen sollten';
$txt['embed_lookups_desc'] = 'Die meisten Funktionen der automatischen Einbettung benötigen Lookups';
$txt['embed_center'] = 'Videos horizontal zentrieren';
$txt['embed_center_desc'] = 'Oder füge "-center" zu den Ankereinstellungen der Videos hinzu (z.B. #ws-center)';
$txt['embed_lookup_titles'] = 'Versuche den Titel auf allen Seiten zu finden';
$txt['embed_lookup_titles_desc'] = '(auch wenn sie nicht unterstützt werden. Man kann nie wissen)';
$txt['embed_incontext'] = 'Einbetten in Sätzen aktivieren';
$txt['embed_nonlocal'] = 'Akzeptiere das lokale Einbinden von externen Webseiten';
$txt['embed_nonlocal_desc'] = 'Falls diese Funktion für Verwirrung sorgt: dieses Funktion ist eine aus Sicherheitsgründen empfohlene Einstellung.';
$txt['embed_max_width'] = 'Maximale Breite von eingebetteten Videos';
$txt['embed_max_width_desc'] = 'Um die Beschränkung aufzuheben leer lassen. 600 für eine Maximale Breite von 600 PX. Größere Videos werden verkleinert. Kleinere Videos enthalten einen Link um sie auf die volle Größe zu maximieren.';
$txt['embed_yq'] = 'Standard YouTube Qualität';
$txt['embed_yq_default'] = 'Standard';
$txt['embed_yq_hd'] = 'HD wenn verfügbar';
$txt['embed_small'] = 'Klein';
$txt['embed_large'] = 'Groß';

$txt['media_admin_settings_title_main'] = 'Haupteinstellungen';
$txt['media_admin_settings_title_security'] = 'Sicherheitseinstellungen';
$txt['media_admin_settings_title_limits'] = 'Limits';
$txt['media_admin_settings_title_tag'] = 'Einbettungscode und [media] Tags';
$txt['media_admin_settings_title_misc'] = 'Verschiedenes';
$txt['media_admin_settings_welcome'] = 'Begrüßung';
$txt['media_admin_settings_welcome_desc'] = 'Um die Standardbegrüßung zu verwenden einfach leer lassen.';
$txt['media_admin_settings_data_dir'] = 'Pfad zum Dateiverzeichnis';
$txt['media_admin_settings_data_dir_desc'] = 'z.B. "media" für /home/www/wedge/media';
$txt['media_admin_settings_max_dir_files'] = 'Maximale Anzahl von Dateien in einem Verzeichnis';
$txt['media_admin_settings_enable_re-rating'] = 'Erneutes Bewerten aktivieren';
$txt['media_admin_settings_use_metadata_date'] = 'Das Upload-Datum auf das Exif-Datum setzen wenn möglich';
$txt['media_admin_settings_use_metadata_date_desc'] = 'Wenn für die Datei Exif-Daten verfügbar sind, wird versucht dieses Datum anstatt der aktuellen Zeit als Uploaddatum zu verwenden.';
$txt['media_admin_settings_title_files'] = 'Datei-Einstellungen';
$txt['media_admin_settings_title_previews'] = 'Vorschaugrößen-Einstellungen';
$txt['media_admin_settings_max_file_size'] = 'Maximale Dateigröße';
$txt['media_admin_settings_max_file_size_desc'] = 'Auf 0 setzen und die Quota Einstellungen für das Finetuning verwenden.';
$txt['media_admin_settings_max_width'] = 'Maximale Breite';
$txt['media_admin_settings_max_height'] = 'Maximale Höhe';
$txt['media_admin_settings_allow_over_max'] = 'Große Bilder automatisch verkleinern';
$txt['media_admin_settings_allow_over_max_desc'] = 'Falls die hochgeladenen Bilder die festgelegte Breite oder Höhe überschreiten, wird versucht, serverseitig die Bilder zu verkleinern. Diese Funktion wird für Server, die an ihrem Limit arbeiten nicht empfohlen. Wähle &quot;Nein&quot; um solche Bilder zu verwerfen.';
$txt['media_admin_settings_upload_security_check'] = 'Sicherheitsüberprüfung beim Upload durchführen';
$txt['media_admin_settings_upload_security_check_desc'] = 'Verhindert das Heraufladen von schädlichen Dateien. Leider kann diese Funktion auch einige normale Dateien zurückweisen. Es wird nicht empfohlen, diese Funktion zu verwenden.';
$txt['media_admin_settings_log_access_errors'] = 'Zugriffsfehler protokollieren';
$txt['media_admin_settings_log_access_errors_desc'] = 'Wenn diese Funktion aktiviert ist, werden alle <em>Zugriff verboten</em> Fehler in der allgemeinen Protokolldatei festgehalten.';
$txt['media_admin_settings_ftp_file'] = 'Dateipfad zur Safe-Mode Datei';
$txt['media_admin_settings_ftp_file_desc'] = 'Mehr Details erhältst du in der MGallerySafeMode.php Datei. Wird benötigt, falls dein Server Safe-Mode aktiviert hat!';
$txt['media_admin_settings_jpeg_compression'] = 'Jpeg Kompression';
$txt['media_admin_settings_jpeg_compression_desc'] = 'Legt die Qualität der zu verkleinernden  Bilder fest. Inklusive Thumbnails und Vorschaubilder. Wähle zwischen 0 (schlechte Qualität, kleine Datei) und 100 (hohe Qualität, große Datei). Die Standardeinstellung von (80) wird empfohlen. Werte zwischen 65 und 85 führen zu den besten Ergebnissen.';
$txt['media_admin_settings_show_extra_info'] = 'Metadaten anzeigen';
$txt['media_admin_settings_show_info'] = 'Metadatenfelder die angezeigt werden sollen';
$txt['media_admin_settings_show_info_desc'] = 'Bilder von Digitalkameras enthalten oft wertvolle Informationen über das Datum, Blenden, etc. Hier kannst du auswählen, welche Daten angezeigt werden sollen und welche nicht.';
$txt['media_admin_settings_num_items_per_page'] = 'Maximale Dateien pro Seite';
$txt['media_admin_settings_max_thumbs_per_page'] = 'Maximale [media] Tags pro Seite';
$txt['media_admin_settings_max_thumbs_per_page_desc'] = 'Maximale Anzahl von [media] Tags, die  auf einer Seite verarbeitet werden können (werden zu Vorschaubildern umgewandelt).';
$txt['media_admin_settings_recent_item_limit'] = 'Limit für neueste Dateien';
$txt['media_admin_settings_random_item_limit'] = 'Limit für zufällige Dateien';
$txt['media_admin_settings_recent_comments_limit'] = 'Limit für neueste Kommentare';
$txt['media_admin_settings_recent_albums_limit'] = 'Limit für die Neuesten Alben';
$txt['media_admin_settings_max_thumb_width'] = 'Maximale Breite von Vorschaubildern (Thumbnails)';
$txt['media_admin_settings_max_thumb_height'] = 'Maximale Höhe von Vorschaubildern (Thumbnails)';
$txt['media_admin_settings_max_preview_width'] = 'Maximale Vorschaubreite';
$txt['media_admin_settings_max_preview_width_desc'] = 'Die Vorschau ist ein anklickbares Bild, welches auf der Hauptseite des Vollbildes angezeigt wird um die Ladezeit zu optimieren. Auf 0 setzen, um diese FUnktion zu deaktivieren. <b>Warnung</b>: Wenn diese Funktion deaktiviert ist, können sehr große Bilder dein Seitenlayout zerstören.';
$txt['media_admin_settings_max_preview_height'] = 'Maximale Vorschauhöhe';
$txt['media_admin_settings_max_preview_height_desc'] = 'Wie oben. Falls Breite oder Höhe auf 0 gesetzt werden, sind die Vorschaubilder deaktiviert.';
$txt['media_admin_settings_max_bigicon_width'] = 'Maximale Breite eines Symbols';
$txt['media_admin_settings_max_bigicon_width_desc'] = 'Alben-Symbole haben ein Vorschaubild (welches die festgelegte Größe der Vorschaubilder (Thumbnails) verwendet) und eine reguläre Größe, die nur auf Alben-Hauptseiten verwendet wird. Diese Funktion legt die Breite für ein reguläres Album fest.';
$txt['media_admin_settings_max_bigicon_height'] = 'Maximale Symbolhöhe';
$txt['media_admin_settings_max_bigicon_height_desc'] = 'Wie oben. Legt die Höhe des Symbols in regulären Alben fest.';
$txt['media_admin_settings_max_title_length'] = 'Maximale Titellänge';
$txt['media_admin_settings_max_title_length_desc'] = 'Maximale Anzahl von Zeichen der Anzeige von Titeln über Vorschaubildern. Auch wenn sie automatisch beschnitten werden, kann der Text vollständig beim herüberfahren mit der Maus angezeigt werden.';
$txt['media_admin_settings_image_handler'] = 'Steuerungsprogramm für Bilddateien';
$txt['media_admin_settings_show_sub_albums_on_index'] = 'Unteralben auf der Startseite anzeigen';
$txt['media_admin_settings_use_zoom'] = 'Zoomedia verwenden (animierte Übergänge)';
$txt['media_admin_settings_use_zoom_desc'] = 'Zoomedia ist ein JavaScript-powered Lightbox Modul, welches Übergänge animiert, wenn auf ein entsprechendes Vorschaubild geklickt wird (Zoom und Ein-/Ausblenden). Deaktivieren, um die Verwendung von Zoomedia in allen Alben zu unterbinden. Wenn Zoomedia aktiviert ist, können Albenbesitzer in ihren Einstellungen die Funktion von Zoomedia aussschalten.';
$txt['media_admin_settings_album_edit_unapprove'] = 'Alben als ungeprüft markieren, wenn sie bearbeitet wurden';
$txt['media_admin_settings_item_edit_unapprove'] = 'Dateien als ungeprüft markieren, wenn sie bearbeitet wurden';
$txt['media_admin_settings_show_linking_code'] = 'Code für die Verlinkung anzeigen';
$txt['media_admin_settings_ffmpeg_installed'] = 'FFMPEG wurde auf diesem Server gefunden. Die Funktionen werden für Videos verwendet. Wenn FFMPEG aktiviert wird, werden Vorschaubilder und weitere Informationen damit erzeugt.';
$txt['media_admin_settings_prev_next'] = 'Vorherige und Nächste Seite als Link anzeigen?';
$txt['media_admin_settings_prev_next_desc'] = 'Aktivieren, um die Seitenanzeige für vorherige/nächste Seiten zu aktivieren.';
$txt['media_admin_settings_default_tag_type'] = 'Vordefinierte Größe für [media] Tags verwenden?';
$txt['media_admin_settings_default_tag_type_desc'] = 'Wähle den Dateityp der angezeigt werden soll, wenn kein Dateityp in [media id=xxx type=xxx] Tags angegeben ist.';
$txt['media_admin_settings_my_docs'] = 'Erlaubte Dokument-Typen';
$txt['media_admin_settings_my_docs_desc'] = 'Du kannst die erlaubten Dateiendungen auswählen, die auf den Server hochgeladen werden dürfen. Verwende ein Komme als Separator (z.B. "zip,pdf"). Die Grundeinstellungen für erlaubte Dateitypen ist: %s';
$txt['media_admin_settings_audio_player_width'] = 'Audio Player Breite';
$txt['media_admin_settings_audio_player_width_desc'] = 'In Pixeln. Grundwert liegt bei 400';
$txt['media_admin_settings_phpini_desc'] = 'Diese Serverseitige Variable schränkt die Größe von Uploads ein. Du kannst die Werte in der php.ini Datei anpassen. Siehe rechte Seite für weitere Informationen ';
$txt['media_admin_settings_clear_thumbnames'] = 'Vorschaubilder URLs in Klartext anzeigen';
$txt['media_admin_settings_clear_thumbnames_desc'] = 'Wenn aktiviert, werden Vorschaubilder mit ihrer direkten URL verlinkt. Spart etwas Serverlast ein, aber ist sicherheitstechnisch nit empfehlenswert.';
$txt['media_admin_settings_album_columns'] = 'Maximale Unteralben pro Zeile';
$txt['media_admin_settings_album_columns_desc'] = 'Grundwert liegt bei 1. Wenn du eine Menge Unteralben hast, kannst du die Werte evtl. auf 2 oder 3 setzen, um die Unteralben auf der Albenhauptseite angezeigt zu bekommen.';
$txt['media_admin_settings_icons_only'] = 'Verwende Symbolkürzel in den Dateicontainern';
$txt['media_admin_settings_icons_only_desc'] = 'Falls aktiviert, werden Dateicontainer mit Symbolen die zu den entsprechenden Einträgen passen verkürzt angezeigt. Zum Beispiel <em>Veröffentlicht von</em>.';
$txt['media_admin_settings_disable_playlists'] = 'Mitglieder Playlists deaktivieren';
$txt['media_admin_settings_disable_playlists_desc'] = 'Damit wird die gesamte Playlistfunktion deaktiviert.';
$txt['media_admin_settings_disable_comments'] = 'Kommentarfunktion deaktivieren';
$txt['media_admin_settings_disable_comments_desc'] = 'Zeigt keine Kommentare zu Dateien an und verhindert das schreiben neuer Kommentare.';
$txt['media_admin_settings_disable_ratings'] = 'Bewertungen deaktivieren';
$txt['media_admin_settings_disable_ratings_desc'] = 'Zeigt keine Bewertungen an und verhindert das Bewerten von Dateien.';

$txt['media_admin_moderation'] = 'Moderation';
$txt['media_admin_moving_album'] = 'Album verschieben';
$txt['media_admin_cancel_moving'] = 'Verschieben abbrechen';
$txt['media_admin_type'] = 'Typ';
$txt['media_admin_edit'] = 'Bearbeiten';
$txt['media_admin_delete'] = 'Löschen';
$txt['media_admin_approve'] = 'Genehmigen';
$txt['media_admin_unapprove'] = 'Genehmigung widerrufen';
$txt['media_admin_before'] = 'Bevor';
$txt['media_admin_after'] = 'Hinter';
$txt['media_admin_child_of'] = 'Unteralbum von';
$txt['media_admin_target'] = 'Ziel';
$txt['media_admin_position'] = 'Position';
$txt['media_admin_membergroups'] = 'Mitgliedergruppen';
$txt['media_admin_membergroups_desc'] = 'Wähle die Mitgliedergruppen mit Zutrittsberechtigungen zu diesen Alben.<br>
<ul class="aevadesc">
	<li>Wenn alle <strong>Primäre Mitgliedergruppen</strong> (diese wurden fett markiert, um deine Aufmerksamkeit zu erregen) markiert sind, haben alle Gruppen Zutriit zu diesen Alben (Gäste ausgenommen).</li>
	<li><strong>Leseberechtigung</strong>: Mitgliedergruppen dürfen das Album und die Dateien sehen und verwenden dabei voreingestellte Berechtigungen (z.B. für Kommentare, Bewertung, etc.)</li>
	<li><strong>Schreibberechtigung</strong>: Mitgliedergruppen dürfen Dateien in das Album laden.</li>
</ul>';
$txt['media_admin_membergroups_primary'] = 'Diese Gruppe wird als primäre Gruppe für ein, oder mehrere Mitglieder verwendet.';
$txt['media_admin_passwd'] = 'Passwort';
$txt['media_admin_move'] = 'Verschieben';
$txt['media_admin_total_submissions'] = 'Gesamte Einsendungen';
$txt['media_maintenance_done'] = 'Wartung durchgeführt';
$txt['media_pruning'] = 'Bereinigen';
$txt['media_admin_maintenance_prune_days'] = ' Minimale Anzahl von Tagen';
$txt['media_admin_maintenance_prune_last_comment_age'] = 'Letzter Kommentar ist älter als';
$txt['media_admin_maintenance_prune_max_coms'] = 'Weniger Kommentare als';
$txt['media_admin_maintenance_prune_max_views'] = 'Weniger Ansichten als';
$txt['media_admin_maintenance_checkfiles_desc'] = 'Sucht nach nicht verwendeten Dateien (die nicht in der Dateitabelle enthalten sind); falls Dateien gefunden werden, können diese Dateien gelöscht werden.';
$txt['media_admin_maintenance_checkorphans'] = 'Suche nach verwaisten Dateien';
$txt['media_admin_maintenance_checkorphans_desc'] = 'Sucht nach verwaisten Dateien ( die nicht mehr in der Dateitabelle enthalten sind); falls Dateien gefunden werden, können diese gelöscht werden. <strong>Warnung</strong>: diese Funktion macht deine Galerie für die Dauer der drei benötigten Phasen <strong>unzugänglich</strong>. In großen Galerien kann dieser Vorgang lange dauern.';
$txt['media_admin_maintenance_regen_all'] = 'Vorschasubilder und Kleinansichten erneuern';
$txt['media_admin_maintenance_regen_embed'] = 'Videovorschaubilder erneuern';
$txt['media_admin_maintenance_regen_thumb'] = 'Kleinansichten (Thumbnails) erneuern';
$txt['media_admin_maintenance_regen_preview'] = 'Vorschaubilder erneuern';
$txt['media_admin_maintenance_regen_all_desc'] = 'Löscht und erneuert alle Kleinansichten (Thumbnails) und Vorschaubilder die von der ursprünglichen Quelle erneuert werden können.';
$txt['media_admin_maintenance_regen_embed_desc'] = 'Löscht und erneuert alle vorhandenen Kleinansichten (Thumbnails), aber nur für <b>eingebettete (externe)</b> Dateien. (YouTube, etc.)';
$txt['media_admin_maintenance_regen_thumb_desc'] = 'Löscht und erneuert alle Kleinansichten (Thumbnails), die von ihrer ursprünglichen Quelle erneuert werden können.';
$txt['media_admin_maintenance_regen_preview_desc'] = 'Löscht und erneuert alle Vorschaubilder, die von ihrer ursprünglichen Quelle erneuert werden können.';
$txt['media_admin_maintenance_operation_pending'] = 'Der aktuelle Prozess wurde pausiert, um eine Überladung des Servers zu verhindern. Er wird in ein paar Sekunden fortgesetzt. Bis jetzt sind aktuell %s von %s Dateien abgearbeitet.';
$txt['media_admin_maintenance_operation_pending_raw'] = 'Der aktuelle Prozess wurde pausiert, um eine Überladung des Servers zu verhindern. Er wird in ein paar Sekunden fortgesetzt.';
$txt['media_admin_maintenance_operation_phase'] = 'Phase %d von %d';
$txt['media_admin_maintenance_recount_desc'] = 'Neuberechnung aller Statistiken. Kann verwendet werden, um falsche Statistiken zu korrigieren';
$txt['media_admin_maintenance_finderrors_desc'] = 'Versucht allgemeine Fehler zu finden, wie z.B. fehlende Dateien (entweder aus der DB oder physikalisch).';
$txt['media_admin_maintenance_prune_desc'] = 'Bereinigt Dateien und Kommentare nach vorgegebenen Parametern.';
$txt['media_admin_maintenance_browse_desc'] = 'Galerie anzeigen und den aktuellen Speicherbedarf jedes Albums anzeigen lassen.';
$txt['media_admin_labels_modlog'] = 'Moderations-Protokoll';
$txt['media_admin_action_type'] = 'Aktion';
$txt['media_admin_reported_item'] = 'Gemeldete Datei';
$txt['media_admin_reported_by'] = 'Gemeldet von';
$txt['media_admin_reported_on'] = 'Gemeldet am';
$txt['media_admin_del_report'] = 'Meldung löschen';
$txt['media_admin_del_report_item'] = 'Gemeldete Datei löschen';
$txt['media_admin_report_reason'] = 'Gemeldeter Grund';
$txt['media_admin_banned_on'] = 'Gesperrt am';
$txt['media_admin_expires_on'] = 'Läuft ab';
$txt['media_never'] = 'Niemals';
$txt['media_admin_ban_type'] = 'Sperrtyp';
$txt['media_admin_ban_type_1'] = 'Komplett';
$txt['media_admin_ban_type_2'] = 'Dateien hochladen';
$txt['media_admin_ban_type_3'] = 'Kommentare schreiben';
$txt['media_admin_ban_type_4'] = 'Dateien hochladen und Kommentieren';
$txt['media_unapproved_items_notice'] = 'Es existieren %2$d ungeprüfte Dateien. <a href="%1$s">Zum anschauen hier klicken</a>';
$txt['media_unapproved_coms_notice'] = 'Es existierene %2$d ungeprüfte Kommentare. <a href="%1$s">Zum anschauen hier klicken</a>';
$txt['media_unapproved_albums_notice'] = 'Es existieren %2$d ungeprüfte Alben. <a href="%1$s">Zum anschauen hier klicken</a>';
$txt['media_reported_items_notice'] = 'Es existieren  %2$d gemeldete Dateien. <a href="%1$s">Zum anschauen hier klicken</a>';
$txt['media_reported_comments_notice'] = 'Es existieren %2$d gemeldete Kommentare. <a href="%1$s">Zum anschauen hier klicken</a>';
$txt['media_admin_modlog_approval_item'] = 'Datei bestätigt <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_ua_item'] = 'Datei nicht bestätigt <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_item'] = 'Datei gelöscht %s (hat auf Bestätigung gewartet)';
$txt['media_admin_modlog_approval_com'] = 'Genehmigter Kommentar <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_com'] = 'Kommentar zu %s gelöscht (hat auf Bestätigung gewartet)';
$txt['media_admin_modlog_approval_album'] = 'Album genehmigt <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_album'] = 'Album gelöscht %s (hat auf Bestätigung gewartet)';
$txt['media_admin_modlog_delete_item'] = 'Datei gelöscht %s';
$txt['media_admin_modlog_delete_album'] = 'Album gelöscht %s';
$txt['media_admin_modlog_delete_comment'] = 'Hat einen Kommentar zu %s gelöscht';
$txt['media_admin_modlog_delete_report_item_report'] = 'Hat eine Meldung zu #%s gelöscht';
$txt['media_admin_modlog_delete_report_comment_report'] = 'Hat eine Meldung zu Kommentar #%s gelöscht';
$txt['media_admin_modlog_delete_item_item_report'] = 'Hat die gemeldete Datei #%s gelöscht';
$txt['media_admin_modlog_delete_item_comment_report'] = 'Hat den gemeldeten Kommentar #%s gelöscht';
$txt['media_admin_modlog_ban_add'] = 'Gesperrt <a href="%s">%s</a>';
$txt['media_admin_modlog_ban_delete'] = 'Sperre aufgehoben von <a href="%s">%s</a>';
$txt['media_admin_modlog_prune_item'] = 'Bereinigte %s Dateien';
$txt['media_admin_modlog_prune_comment'] = 'Bereinigte %s Kommentare';
$txt['media_admin_modlog_move'] = 'Verschob <a href=%s">%s</a> von Album <a href="%s">%s</a> nach <a href="%s">%s</a>';
$txt['media_admin_modlog_qsearch'] = 'Schnellsuche nach Mitgliedern';
$txt['media_admin_modlog_filter'] = 'Moderations-Protokolle gefiltert nach <a href="%s">%s</a>';
$txt['media_admin_view_image'] = 'Bild anzeigen';
$txt['media_admin_ftp_files'] = 'Dateien innerhalb des FTP Ordners';
$txt['media_admin_profile_add'] = 'Profil hinzufügen';
$txt['media_admin_prof_name'] = 'Profil-Name';
$txt['media_admin_create_prof'] = 'Profil erstellen';
$txt['media_admin_members'] = 'Mitglieder';
$txt['media_admin_prof_del_switch'] = 'Profil zu denen die Alben verknüpft werden';
$txt['media_quota_profile'] = 'Quota Profil von Mitgliedergruppen';
$txt['media_album_hidden'] = 'Anzeige deaktivieren';
$txt['media_album_hidden_desc'] = 'Aktivieren, um alle außer Administratoren vom Betreten des Albums abzuhalten. Der Zugriff von speziellen Mitgliedergruppen bleibt davon unberührt. Eignet sich hervorragend als Container für Blogs oder Forenbeiträge.';
$txt['media_allowed_members'] = 'Erlaubte Mitglieder (Leseberechtigung)';
$txt['media_allowed_members_desc'] = 'Gebe einen oder mehrere Benutzernamen ein, die dieses Album sehen dürfen. Unabhängig von ihrer Gruppenmitgliedschaft.';
$txt['media_allowed_write'] = 'Erlaubte Mitglieder (Schreibrechte)';
$txt['media_allowed_write_desc'] = 'Gebe einen oder mehrere Benutzernamen ein, die Dateien in dieses Album hinzufügen können. Unabhängig von ihrer Gruppenmitgliedschaft.';
$txt['media_denied_members'] = 'Abgelehnte Mitglieder (Leseberechtigung)';
$txt['media_denied_members_desc'] = 'Gebe ein oder mehrere Benutzernamen ein, die dieses Album nicht sehen dürfen. Unabhängig von ihrer Gruppenmitgliedschaft.';
$txt['media_denied_write'] = 'Abgelehnte Mitglieder (Schreibrechte)';
$txt['media_denied_write_desc'] = 'Gebe einen oder mehrere Benutzernamen ein, die keine Dateien in dieses Album hinzufügen können. Unabhängig von ihrer Gruppenmitgliedschaft.';
$txt['media_admin_wselected'] = 'Mit ausgewählten';
$txt['media_admin_select_or'] = 'Oder...';
$txt['media_admin_apply_perm'] = 'Berechtigung hinzufügen';
$txt['media_admin_clear_perm'] = 'Berechtigung löschen';
$txt['media_admin_set_mg_perms'] = 'Setze Berechtigungen wie diese Gruppe';

// Admin error strings
$txt['media_admin_album_confirm'] = 'Möchtest du wirklich dieses Album löschen? Alle Kommentare in diesem Album werden ebenfalls gelöscht.';
$txt['media_admin_name_left_empty'] = 'Name ist leer';
$txt['media_admin_invalid_target'] = 'Ungültiges Ziel angegeben';
$txt['media_admin_invalid_position'] = 'Ungültige Position ausgewählt';
$txt['media_admin_prune_invalid_days'] = 'Ungültige &quot;Tage&quot; Eingabe angegeben';
$txt['media_admin_no_albums'] = 'Keine Alben ausgewählt';
$txt['media_admin_rm_selected'] = 'Ausgewählte löschen';
$txt['media_admin_rm_all'] = 'Alle löschen';
$txt['media_report_not_found'] = 'Meldung konnte nicht gefunden werden';
$txt['media_admin_bans_mems_empty'] = 'Es wurden keine Mitglieder ausgewählt';
$txt['media_admin_bans_mems_not_found'] = 'Ausgewählte Mitglieder konnten nicht gefunden werden';
$txt['media_ban_not_found'] = 'Sperre nicht gefunden';
$txt['media_admin_already_banned'] = 'Benutzer ist bereits gesperrt!';
$txt['media_admin_unique_permission'] = 'Bitte nur eine Option auswählen';
$txt['media_admin_quick_none'] = 'Keine Option ausgewählt';
$txt['media_admin_invalid_groups'] = 'Eine ungültige Gruppenauswahl wurde getroffen. Entweder existiert diese Gruppe nicht, oder falls du Berechtigungen kopieren willst, stelle bitte sicher, dass auch eine Gruppe ausgewählt wurde.';

// Admin help strings
$txt['media_admin_desc'] = 'Media-Admin';
$txt['media_admin_settings_desc'] = 'Hier befindet sich dein Admin-Panel um Einstellungen an der Media-Galerie vorzunehmen.';
$txt['media_admin_embed_desc'] = 'Hier befindet sich das Auto-Einbinden Admin-Panel. Auf dieser Seite kannst du das automatische einbinden von externen Dateien, wie z.B. YouTube einstellen. Zusätzlich können hier auch erlaubte Webseiten verwaltet werden.';
$txt['media_admin_albums_desc'] = 'Hier befindet sich dein Album Admin-Panel. Auf dieser Seite kannst du deine Alben konfigurieren und verschiedene Einstellungen, wie z.B. das verschieben von Alben, vornehmen . Mit Klick auf den <strong>+</strong> Button erhälst du detaillierte Informationen über das entsprechende Album.';
$txt['media_admin_subs_desc'] = 'Hier befindet sich dein Admin-Panel für hochgeladene Dateien. Auf dieser Seite kannst du Dateien ansehen, freigeben oder löschen. Ebenfalls Kommentare und ALben freischalten';
$txt['media_admin_maintenance_desc'] = 'Hier befindet sich der Wartungsbereich der Mediengalerie. Dieser Bereich enthält ein paar nützliche Funktionen';
$txt['media_admin_modlog_desc'] = 'Hier befindet sich dein Moderations-Protokoll. Behalte den Überblick über alle Aktivitäten von Moderatoren in deiner Galerie.';
$txt['media_admin_reports_desc'] = 'Hier befindet sich dein Admin-Panel für gemeldete Beiträge. Hier kannst du gemeldete Beiträge bearbeiten, löschen oder freigeben';
$txt['media_admin_bans_desc'] = 'Hier befindet sich dein Admin-Panel für Sperren (Bans).';
$txt['media_admin_about_desc'] = 'Willkommen im Administrationsmenü deiner Mediengalerie!';
$txt['media_admin_passwd_desc'] = 'Schicke es an User, mit denen du das Album teilen möchtest. Andernfalls leer lassen.';
$txt['media_admin_maintenance_finderror_pending'] = 'Das Script wird weiterhin ausgeführt. Aktuell sind %s von %s Dateien bearbeitet.<br><br><a href="%s">Hier klicken um fortzufahren.</a> Bitte sicherstellen, dass 1-2 Sekunden Pause eingehalten werden, um eine Überbeanspruchung des Servers zu vermeiden.';
$txt['media_admin_finderrors_1'] = 'Die nachfolgenden Fehler wurden bei der Suche nach Fehlern entdeckt';
$txt['media_admin_finderrors_missing_db_file'] = 'Der Datenbankeintrag der Datei #%s, verwendet mit #<a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_db_thumb'] ='Der Datenbankeintrag der Kleinansichten (Thumbnails)  #%s, verknüpft mit #<a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_db_preview'] ='Der Datenankeintrag der Vorschaudatei #%s, verknüpft mit <a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_physical_file'] = 'Die physikalische Datei #%s, verknüpft mit <a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_physical_thumb'] = 'Das physikalische Thumbnail #%s, verknüpft mit <a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_physical_preview'] = 'Das physikalische Vorshaubild #%s, verknüpft mit <a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_album'] = 'Das Album #%s, verknüpft mit der Datei <a href="%s">%s</a>, ist nicht vorhanden.';
$txt['media_admin_finderrors_missing_last_comment'] = 'Der Kommentar #%s, verknüpft mit der Datei <a href="%s">%s</a> ist nicht vorhanden.';
$txt['media_admin_finderrors_parent_album_access'] = 'Album #%s wurde aktualisiert, um Gruppen zu entfernen, die keinen Zutritt zu den Hauptalbum haben.';
$txt['media_admin_finderrors_done'] = 'Die Überprüfung nach Fehlern ist abgeschlossen. Keine Fehler gefunden!';
$txt['media_admin_prune_done_items'] = 'Bereinigung der Dateien ist abgeschlossen! %s Einträge, %s Kommentare und %s Dateien wurden gelöscht';
$txt['media_admin_prune_done_comments'] = 'Bereinigung der Kommentare ist abgeschlossen! %s Kommentare wurden gelöscht';
$txt['media_admin_maintenance_prune_item_help'] = 'Dateibereinigung: du kannst Dateien bereinigen, die älter als &quot;x&quot; Tage sind. Den Wert kannst du unterhalb festlegen.';
$txt['media_admin_maintenance_prune_com_help'] = 'Kommentarbereinigung: du kannst Kommentare bereinigen, die älter als &quot;x&quot; Tage sind. Den Wert kannst du  unterhalb festlegen.';
$txt['media_admin_maintenance_checkfiles_done'] = 'Nicht mehr verwendete Dateien wurden entfernt. Gesamtmenge: %s Dateien mit einem Speicherbedarf von %s Kilobytes .';
$txt['media_admin_maintenance_checkfiles_no_files'] = 'Keine zusätzlichen Dateien gefunden';
$txt['media_admin_maintenance_checkfiles_found'] = 'Es wurden %s nicht mehr verwendete Dateien mit einem Speicherbedarf von %s Kilobytes gefunden. <a href="%s">Hier klicken</a> um diese Dateien zu entfernen.';
$txt['media_admin_maintenance_checkorphans_done'] = 'Alle verwaisten Dateien wurden entfernt. Insgesamt %s Dateien:';
$txt['media_admin_maintenance_checkorphans_no_files'] = 'Keine verwaisten Dateien gefunden';
$txt['media_admin_maintenance_clear_pending'] = 'Das Script arbeitet noch. Aktuell wurden %s von %s Dateien abgearbeitet.<br><br>Bitte <a href="%s">hier klicken</a> um mit der Wartung fortzufahren.';
$txt['media_admin_maintenance_clear_done'] = 'Alle Dateien wurden erfolgreich umbenannt.';
$txt['media_admin_installed_on'] = 'Installiert am';
$txt['media_admin_icon_edit_desc'] = 'Wenn du das Symbol erneut hochlädst, wird das alte Symbol überschrieben. Leer lasen, um das bisherige Symbol';
$txt['media_admin_bans_mems_empty'] = 'Es wurden keine Mitglieder ausgewählt';
$txt['media_admin_expires_on_help'] = 'Sollte in &quot;Tagen&quot; von heute an eingegeben werden';
$txt['media_admin_modlog_desc'] = 'Dies ist das Moderations-Protokoll. Hier findest du eine Übersicht aller Aktivitäten, die Moderatorentätigkeit erfordert haben. Wenn du die Einträge löschst, sind sie für immer gelöscht.';
$txt['media_admin_ftp_desc'] = 'Dieser Bereich erlaubt es dir, Dateien von einem externen Verzeichnis auf den Server zu laden. Hilfreich bei sehr großen Dateien, die mit PHP nicht hochgeladen werden können.';
$txt['media_admin_ftp_help'] = 'Dies ist die Auflistung aller Dateien innerhalb des {Data_dir}/ftp Ordners. Bitte wähle den Zielordner für jede Datei aus um den Import zu starten.';
$txt['media_admin_ftp_halted'] = 'Das Script legt eine kurze Pause ein, um eine Überlastung des Servers zu vermeiden. Aktuell wurden %s von %s Dateien importiert. Der Import setzt sich automatisch fort.';
$txt['media_admin_perms_desc'] = 'Hier kannst du verschiedenen Berechtigungsprofile definieren, die den Albenzugriff definieren.';
$txt['media_admin_prof_del_switch_help'] = 'Falls du ein aktuell verwendetes Profil löschen möchtest, benötigt das Album eine Zuteilung auf ein anderes Profil .';
$txt['media_admin_quotas_desc'] = 'Hier kannst du die Quotas für die Mitgliedergruppen verwalten';
$txt['media_admin_perms_warning'] = '<strong>Warnung</strong>: diese Seite ist ausschließlich für Albenberechtigungen ausgelegt. Generelle Zugangsberechtigungen müssen für jede Mitgliedergruppe im regulären <a href="%s">Administrations-Panel</a> angegeben werden.';

// Per-album Permissions
$txt['permissionname_media_download_item'] = 'Dateien herunterladen';
$txt['permissionname_media_add_videos'] = 'Videos hinzufügen';
$txt['permissionname_media_add_audios'] = 'Audiodateien hinzufügen';
$txt['permissionname_media_add_docs'] = 'Dokumente hinzufügen';
$txt['permissionname_media_add_embeds'] = 'Eingebette Dateien hinzufügen';
$txt['permissionname_media_add_images'] = 'Bilder hinzufügen';
$txt['permissionname_media_rate_items'] = 'Dateien bewerten';
$txt['permissionname_media_edit_own_com'] = 'Eigene Kommentare bearbeiten';
$txt['permissionname_media_report_com'] = 'Kommentar melden';
$txt['permissionname_media_edit_own_item'] = 'Eigene Dateien bearbeiten';
$txt['permissionname_media_comment'] = 'Kommentar zu den Dateien';
$txt['permissionname_media_report_item'] = 'Dateien melden';
$txt['permissionname_media_auto_approve_com'] = 'Kommentare automatisch freigeben';
$txt['permissionname_media_auto_approve_item'] = 'Dateien automatisch freigeben';
$txt['permissionname_media_multi_upload'] = 'Massen-Upload';
$txt['permissionname_media_whoratedwhat'] = 'Wer hat was bewertet';
$txt['permissionname_media_multi_download'] = 'Massen-Download';

// Custom fields
$txt['media_cf_invalid'] = 'Die übermittelte Eingabe für %s ist ungültig';
$txt['media_cf_empty'] = 'Feld %s wurde nicht ausgefüllt';
$txt['media_cf_bbc'] = 'Dieses Feld darf BBCode verwenden';
$txt['media_cf_required'] = 'Dieses Feld wird benötigt';
$txt['media_cf_desc'] = 'Hier kannst du benutzerdefinierte Felder verwalten';
$txt['media_admin_labels_fields'] = 'Benutzerdefinierte Felder';
$txt['media_cf_name'] = 'Feldname';
$txt['media_cf_type'] = 'Feldtyp';
$txt['media_cf_req'] = 'Benötigt';
$txt['media_cf_searchable'] = 'Verfügbar in der Suche';
$txt['media_cf_bbcode'] = 'BBC';
$txt['media_cf_editing'] = 'Hinzufügen/Bearbeiten eines benutzerdefinierten Feldes';
$txt['media_cf_text'] = 'Text';
$txt['media_cf_radio'] = 'Radio Buttons';
$txt['media_cf_checkbox'] = 'Auswahlboxen';
$txt['media_cf_textbox'] = 'Text-Box';
$txt['media_cf_select'] = 'Auswahlfeld als Dropdown';
$txt['media_cf_options'] = 'Optionen';
$txt['media_cf_options_desc'] = 'Füge Optionen für dieses Feld hinzu. Nur gültig, wenn das Feld als Feldtyp Auswahlbox, Radio-Button, oder Auswahlfeld angegeben wurde. Kommas als Trennzeichen verwenden';
