<?php
// Version: 2.0; ManageMedia

$txt['embed_enabled'] = '<strong>Включить автовнедрение роликов</strong>';
$txt['embed_enabled_desc'] = 'Обязательный параметр';
$txt['embed_lookups'] = 'Включить функцию поиска (Lookups)';
$txt['embed_lookup_success'] = 'Эта функция БУДЕТ работать на вашем сервере';
$txt['embed_lookup_fail'] = 'Эта функция НЕ будет работать на вашем сервере';
$txt['embed_max_per_post'] = 'Максимальное количество внедряемых элементов в сообщении';
$txt['embed_max_per_page'] = 'Максимальное количество внедряемых элементов на странице';
$txt['embed_max_warning'] = 'Избыток Flash-роликов ухудшает производительность вашего браузера';
$txt['embed_quotes'] = 'Разрешить внедрение элементов в цитатах';
$txt['embed_mov'] = 'Файлы Quicktime (*.mov)';
$txt['embed_real'] = 'Файлы Real Media (*.ram;*.rm)';
$txt['embed_wmp'] = 'Файлы Windows Media (*.wmv;*.wma)';
$txt['embed_swf'] = 'Flash-анимация (*.swf)';
$txt['embed_flv'] = 'Flash-видео (*.flv)';
$txt['embed_divx'] = 'Файлы Divx (*.divx)';
$txt['embed_avi'] = 'Файлы AVI (*.avi)';
$txt['embed_mp3'] = 'Файлы MP3 (*.mp3)';
$txt['embed_mp4'] = 'Файлы MP4 (*.mp4)';
$txt['embed_ext'] = 'Разрешённые типы файлов';
$txt['embed_fix_html'] = 'Исправлять использование внедренного HTML-кода с внедряемой ссылкой';
$txt['embed_includeurl'] = 'Включать оригинальную ссылку';
$txt['embed_includeurl_desc'] = '(для сайтов, не имеющих её в плеере)';
$txt['embed_local'] = 'Интеграция локальных файлов [исключая вложения]';
$txt['embed_local_desc'] = 'Локальный файл — файл, находящийся на этом же сервере. Но это не означает, что можно интегрировать ЛЮБЫЕ файлы такого же типа откуда попало.';
$txt['embed_denotes'] = '(Сайты, помеченные *, требуют активации функции поиска)';
$txt['embed_fish'] = '(Сайты, помеченные *, требуют активации функции поиска, однако поиск НЕ будет работать на вашем сервере.<br>Следовательно, URL-адрес каждого внедряемого элемента придется вводить вручную, интеграция работать НЕ будет.)';
$txt['embed_pop_sites'] = 'Популярные сайты';
$txt['embed_video_sites'] = 'Видеосайты';
$txt['embed_audio_sites'] = 'Аудиосайты';
$txt['embed_other_sites'] = 'Остальные сайты';
$txt['embed_adult_sites'] = 'Сайты для взрослых';
$txt['embed_custom_sites'] = 'Пользовательские сайты';
$txt['embed_disable'] = 'Отключить интеграцию';
$txt['embed_titles'] = 'Хранить и отображать заголовки видеороликов';
$txt['embed_titles_desc'] = '(если сайт поддерживается Wedge)';
$txt['embed_titles_yes'] = 'Да, искать и отображать';
$txt['embed_titles_yes2'] = 'Да, но не сохранять никаких обновлений';
$txt['embed_titles_no'] = 'Нет, но сохранять результат поиска для дальнейшего использования';
$txt['embed_titles_no2'] = 'Нет, не хранить и не отображать';
$txt['embed_inlinetitles'] = 'Отображать заголовок внутри видеоэскиза';
$txt['embed_inlinetitles_desc'] = '(для поддерживаемых сайтов, таких как YouTube и Vimeo)';
$txt['embed_inlinetitles_yes'] = 'Да';
$txt['embed_inlinetitles_maybe'] = 'Только если заголовок ещё не сохранен';
$txt['embed_inlinetitles_no'] = 'Нет';
$txt['embed_noscript'] = 'Использовать предыдущую систему интеграции (без Javascript)';
$txt['embed_noscript_desc'] = 'Используйте только в случае проблем с совместимостью';
$txt['embed_lookups_desc'] = 'Большинство функций автовнедрения требуют включения данной опции';
$txt['embed_center'] = 'Центрировать видео по горизонтали';
$txt['embed_center_desc'] = 'Или добавлять &laquo;-center&raquo; к&nbsp;любым настройкам, связанным с&nbsp;видео (н.&nbsp;п. #ws-center)';
$txt['embed_lookup_titles'] = 'Пытаться искать заголовки на всех сайтах';
$txt['embed_lookup_titles_desc'] = '(даже если они не поддерживаются — вы никогда не узнаете)';
$txt['embed_incontext'] = 'Разрешить внедрение элементов в предложениях';
$txt['embed_nonlocal'] = 'Принимать внешние веб-сайты в добавление к локальным';
$txt['embed_nonlocal_desc'] = 'Не рекомендуется включать эту функцию (из соображений безопасности).';
$txt['embed_max_width'] = 'Максимальная ширина встраиваемых видеороликов';
$txt['embed_max_width_desc'] = 'Оставьте пустым для отключения. Введите 600 для установки максимальной ширины в 600 пикселей. Видео, превышающее по размерам заданное, будет уменьшено; к видео, ширина которого меньше заданного, будет добавлена ссылка для увеличения размера до максимального.';
$txt['embed_yq'] = 'Стандартное качество YouTube';
$txt['embed_yq_default'] = 'По умолчанию';
$txt['embed_yq_hd'] = 'HD-качество, если возможно';
$txt['embed_small'] = 'Низкое качество';
$txt['embed_large'] = 'Среднее качество';

$txt['media_admin_settings_title_main'] = 'Главные настройки';
$txt['media_admin_settings_title_security'] = 'Параметры безопасности';
$txt['media_admin_settings_title_limits'] = 'Ограничения';
$txt['media_admin_settings_title_tag'] = 'Внедряемый код и тег [media]';
$txt['media_admin_settings_title_misc'] = 'Разное';
$txt['media_admin_settings_welcome'] = 'Приветствие';
$txt['media_admin_settings_welcome_desc'] = 'Оставьте пустым для использования стандартного приветствия.';
$txt['media_admin_settings_data_dir'] = 'Директория для хранения данных';
$txt['media_admin_settings_data_dir_desc'] = 'Например, "media" для /home/www/wedge/media';
$txt['media_admin_settings_max_dir_files'] = 'Максимальное количество файлов в директории';
$txt['media_admin_settings_enable_re-rating'] = 'Разрешить пользователям изменять оценки';
$txt['media_admin_settings_use_metadata_date'] = 'Использовать дату и время из тегов Exif при загрузке элементов (если это возможно)';
$txt['media_admin_settings_use_metadata_date_desc'] = 'При обнаружении соответствующих данных дата и время будут взяты из тегов элемента.';
$txt['media_admin_settings_title_files'] = 'Параметры файлов';
$txt['media_admin_settings_title_previews'] = 'Размеры превью и эскизов';
$txt['media_admin_settings_max_file_size'] = 'Максимальный размер файла';
$txt['media_admin_settings_max_file_size_desc'] = 'Установите 0 и используйте раздел "Квоты групп" для тонкой настройки.';
$txt['media_admin_settings_max_width'] = 'Максимальная ширина изображения';
$txt['media_admin_settings_max_height'] = 'Максимальная высота изображения';
$txt['media_admin_settings_allow_over_max'] = 'Разрешить изменение размера больших изображений';
$txt['media_admin_settings_allow_over_max_desc'] = 'При загрузке очень больших изображений сервер будет пытаться изменить их в соответствии с заданным размером. Не рекомендуется к использованию на перегруженных серверах. Выберите &quot;Нет&quot; для отказа от таких изображений.';
$txt['media_admin_settings_upload_security_check'] = 'Проверять загружаемые файлы';
$txt['media_admin_settings_upload_security_check_desc'] = 'Запрещает загрузку вредоносных файлов, но иногда может помешать и загрузке нормальных файлов. Не рекомендуется включать, по крайней мере до тех пор, пока некоторые реально, реально тупые пользователи IE не столкнутся с данной проблемой.';
$txt['media_admin_settings_log_access_errors'] = 'Лог ошибок доступа';
$txt['media_admin_settings_log_access_errors_desc'] = 'Если включено, все <em>ошибки доступа</em>, связанные с медиатекой, будут отправляться в общий лог ошибок.';
$txt['media_admin_settings_ftp_file'] = 'Путь к файлу безопасного режима (Safe Mode)';
$txt['media_admin_settings_ftp_file_desc'] = 'Смотрите файл MGallerySafeMode.php для дополнительных сведений. Необходимо, если на сервере включен Безопасный режим!';
$txt['media_admin_settings_jpeg_compression'] = 'Сжатие JPEG';
$txt['media_admin_settings_jpeg_compression_desc'] = 'Определяет качество и размер изображения, в том числе и эскиза изображения. Укажите значение между 0 (плохое качество, маленький файл) и 100 (высокое качество, большой файл). Рекомендуемое значение по умолчанию — 80. Значения между 65 и 85 являются оптимальными.';
$txt['media_admin_settings_show_extra_info'] = 'Показывать метаданные';
$txt['media_admin_settings_show_info'] = 'Список метаданных для показа';
$txt['media_admin_settings_show_info_desc'] = 'В фотографиях, полученных с помощью цифровых устройств, нередко хранится такая полезная информация, как <strong>Дата снимка</strong> и пр. Выберите, какую информацию следует показывать в сведениях об элементах.';
$txt['media_admin_settings_num_items_per_page'] = 'Максимальное количество элементов на странице';
$txt['media_admin_settings_max_thumbs_per_page'] = 'Максимальное количество тегов [media] на странице';
$txt['media_admin_settings_max_thumbs_per_page_desc'] = 'Указанное количество тегов [media] будет преобразовываться в соответствующие элементы, все остальные будут проигнорированы.';
$txt['media_admin_settings_recent_item_limit'] = 'Максимальное количество элементов в блоке "Последние элементы"';
$txt['media_admin_settings_random_item_limit'] = 'Максимальное количество элементов в блоке "Случайные элементы"';
$txt['media_admin_settings_recent_comments_limit'] = 'Максимальное количество элементов в блоке "Последние комментарии"';
$txt['media_admin_settings_recent_albums_limit'] = 'Максимальное количество альбомов в блоке "Последние альбомы"';
$txt['media_admin_settings_max_thumb_width'] = 'Максимальная ширина эскиза';
$txt['media_admin_settings_max_thumb_height'] = 'Максимальная высота эскиза';
$txt['media_admin_settings_max_preview_width'] = 'Максимальная ширина превью';
$txt['media_admin_settings_max_preview_width_desc'] = 'Превью — это уменьшенное (для ускорения загрузки) изображение, при клике на которое отображается оригинал. Установите значение 0 для отключения функции превью. <b>Внимание</b>: если функция отключена, слишком большие картинки могут искажать шаблон форума.';
$txt['media_admin_settings_max_preview_height'] = 'Максимальная высота превью';
$txt['media_admin_settings_max_preview_height_desc'] = 'То же самое (см. выше). Если ширина или высота установлена в 0, функция превью будет отключена..';
$txt['media_admin_settings_max_bigicon_width'] = 'Максимальная ширина иконки';
$txt['media_admin_settings_max_bigicon_width_desc'] = 'Значки альбомов имеют миниатюру (размер задаётся в секции "Максимальный размер эскиза") и обычный размер, используемый только на странице альбома. Данный параметр отвечает за установку ширины иконки альбома.';
$txt['media_admin_settings_max_bigicon_height'] = 'Максимальная высота иконки';
$txt['media_admin_settings_max_bigicon_height_desc'] = 'То же самое (см. выше). Установка высоты иконки альбома.';
$txt['media_admin_settings_max_title_length'] = 'Максимальная длина заголовка';
$txt['media_admin_settings_max_title_length_desc'] = 'Максимальное количество символов для вывода названий над миниатюрами. Если отключить, названия будут отображаться в качестве всплывающих подсказок над элементами.';
$txt['media_admin_settings_image_handler'] = 'Обработчик изображений';
$txt['media_admin_settings_show_sub_albums_on_index'] = 'Показывать вложенные альбомы на главной странице медиатеки';
$txt['media_admin_settings_use_zoom'] = 'Использовать Zoomedia (анимированные переходы)';
$txt['media_admin_settings_use_zoom_desc'] = 'Zoomedia это модуль lightbox, работающий на JavaScript, добавляющий анимированные переходы при нажатии на превьюшки (масштабирование и постепенное появление/затухание). Отключите, чтобы запретить использование Zoomedia во всех альбомах. Если включено, то владельцы альбомов могут самостоятельно отключать Zoomedia в настройках собственных альбомов.';
$txt['media_admin_settings_album_edit_unapprove'] = 'Повторное одобрение альбомов после их изменения';
$txt['media_admin_settings_item_edit_unapprove'] = 'Повторное одобрение элементов после их изменения';
$txt['media_admin_settings_show_linking_code'] = 'Отображать блок с ББ-кодом для вставки просматриваемого элемента в сообщения на форуме';
$txt['media_admin_settings_ffmpeg_installed'] = 'Библиотека FFMPEG была обнаружена на вашем сервере, её функции будут использоваться для обработки видеофайлов, создания эскизов и извлечения дополнительной информации из загружаемых файлов.';
$txt['media_admin_settings_prev_next'] = 'Отображать ссылки &laquo;Предыдущий&raquo; и&nbsp;&laquo;Следующий&raquo;?';
$txt['media_admin_settings_prev_next_desc'] = 'Включите для отображения текстовых ссылок или эскизов для перехода между элементами.';
$txt['media_admin_settings_default_tag_type'] = 'Стандартный размер элемента при использовании тега [media]?';
$txt['media_admin_settings_default_tag_type_desc'] = 'Выберите, что отображать при вставке тега без явного указания типа ([media id=xxx type=xxx]).';
$txt['media_admin_settings_my_docs'] = 'Разрешённые типы документов';
$txt['media_admin_settings_my_docs_desc'] = 'Загрузка файлов указанных типов будет разрешена. Используйте запятую для разделения (например: "zip,pdf"). Поддерживаемые типы файлов: %s';
$txt['media_admin_settings_audio_player_width'] = 'Ширина аудио плеера';
$txt['media_admin_settings_audio_player_width_desc'] = 'В пикселях. По умолчанию 400';
$txt['media_admin_settings_phpini_desc'] = 'Это серверная переменная, ограничивающая максимальный размер закачиваемых файлов. Можно изменить этот параметр с помощью php.ini или установок в файле .htaccess';
$txt['media_admin_settings_clear_thumbnames'] = 'Оставлять URL-адреса эксизов в чистом виде (прямые URL)';
$txt['media_admin_settings_clear_thumbnames_desc'] = 'URL-адрес эскиза будет содержать физический адрес файла. Это снизит нагрузку на сервер, однако не очень безопасно.';
$txt['media_admin_settings_album_columns'] = 'Максимальное количество вложенных альбомов в одном ряду';
$txt['media_admin_settings_album_columns_desc'] = 'По умолчанию 1. При наличии нескольких вложенных альбомов можно установить, к примеру, 2 или 3 альбома в одном ряду.';
$txt['media_admin_settings_icons_only'] = 'Показывать значки вместо текста';
$txt['media_admin_settings_icons_only_desc'] = 'Если включено, в информации под эскизом каждого элемента, вместо слов <em>Просмотров</em> и <em>Автор</em>, будут отображаться соответствующие значки.';
$txt['media_admin_settings_disable_playlists'] = 'Отключить пользовательские плейлисты';
$txt['media_admin_settings_disable_playlists_desc'] = 'Полное отключение функции плейлистов.';
$txt['media_admin_settings_disable_comments'] = 'Отключить комментарии к элементам';
$txt['media_admin_settings_disable_comments_desc'] = 'Не показывать существующие комментарии и запретить комментирование вообще.';
$txt['media_admin_settings_disable_ratings'] = 'Отключить рейтинг элементов';
$txt['media_admin_settings_disable_ratings_desc'] = 'Не показывать существующие оценки и запретить выставление оценок вообще.';

$txt['media_admin_moderation'] = 'Модерация';
$txt['media_admin_moving_album'] = 'Перемещение альбома';
$txt['media_admin_cancel_moving'] = 'Отменить перемещение';
$txt['media_admin_type'] = 'Тип';
$txt['media_admin_edit'] = 'Изменить';
$txt['media_admin_delete'] = 'Удалить';
$txt['media_admin_approve'] = 'Одобрить';
$txt['media_admin_unapprove'] = 'Отклонить';
$txt['media_admin_before'] = 'До';
$txt['media_admin_after'] = 'После';
$txt['media_admin_child_of'] = 'Вложить в';
$txt['media_admin_target'] = 'Цель';
$txt['media_admin_position'] = 'Позиция';
$txt['media_admin_membergroups'] = 'Группы';
$txt['media_admin_membergroups_desc'] = 'Отметьте группы, которым разрешен доступ к&nbsp;элементам этого альбома.<br>
<ul class="aevadesc">
	<li>Если выбрать группу <strong>Обычные пользователи</strong>, то&nbsp;альбом будет доступен всем зарегистрированным пользователям форума.</li>
	<li>Права на&nbsp;<strong>чтение</strong>: члены группы могут просматривать альбом и&nbsp;элементы в&nbsp;нем, и&nbsp;использовать установленные разрешения (комментирование, оценивание и&nbsp;т.&nbsp;д.)</li>
	<li>Права на&nbsp;<strong>запись</strong>: члены группы могут добавлять элементы в&nbsp;альбом.</li>
</ul>';
$txt['media_admin_membergroups_primary'] = 'Эта группа основана на группе с одним или более участниками.';
$txt['media_admin_passwd'] = 'Пароль';
$txt['media_admin_move'] = 'Переместить';
$txt['media_admin_total_submissions'] = 'Всего материалов';
$txt['media_maintenance_done'] = 'Обработка завершена';
$txt['media_pruning'] = 'Чистка';
$txt['media_admin_maintenance_prune_days'] = ' Минимальное число дней';
$txt['media_admin_maintenance_prune_last_comment_age'] = 'Последний комментарий позже';
$txt['media_admin_maintenance_prune_max_coms'] = 'С количеством комментариев меньше чем';
$txt['media_admin_maintenance_prune_max_views'] = 'С количеством просмотров меньше чем';
$txt['media_admin_maintenance_checkfiles_desc'] = 'Поиск неиспользуемых файлов (не найденных в таблице media_items); при обнаружении их можно будет удалить.';
$txt['media_admin_maintenance_checkorphans'] = 'Поиск ненужных файлов';
$txt['media_admin_maintenance_checkorphans_desc'] = 'Поиск ненужных файлов, которые больше не используются (не найденных в таблице media_files); при обнаружении их можно будет удалить. <strong>Предупреждение</strong>: запуск этой задачи сделает вашу галерею <strong>временно недоступной</strong>, пока не завершатся 3 фазы операции. В большой галерее это может занять много времени.';
$txt['media_admin_maintenance_regen_all'] = 'Пересоздать все эскизы и превью';
$txt['media_admin_maintenance_regen_embed'] = 'Пересоздать эскизы видео';
$txt['media_admin_maintenance_regen_thumb'] = 'Пересоздать эскизы';
$txt['media_admin_maintenance_regen_preview'] = 'Пересоздать превью';
$txt['media_admin_maintenance_regen_all_desc'] = 'Удаление всех ранее созданных эскизов и превью с последующей попыткой их создать.';
$txt['media_admin_maintenance_regen_embed_desc'] = 'Удаление эскизов для <b>внедряемых</b> элементов (YouTube и&nbsp;т.&nbsp;д.) с&nbsp;последующей попыткой их&nbsp;создать.';
$txt['media_admin_maintenance_regen_thumb_desc'] = 'Удаление эскизов для элементов с последующей попыткой их создать.';
$txt['media_admin_maintenance_regen_preview_desc'] = 'Удаление превью для элементов с последующей попыткой их создать.';
$txt['media_admin_maintenance_operation_pending'] = 'Пересоздание было прервано для предотвращения перегрузки сервера. Операция автоматически продолжится через пару секунд. Обработано %s из %s элементов.';
$txt['media_admin_maintenance_operation_pending_raw'] = 'Текущая операция была приостановлена во избежание перегрузки сервера; она автоматически продолжится через несколько секунд.';
$txt['media_admin_maintenance_operation_phase'] = 'Фаза %d из %d';
$txt['media_admin_maintenance_recount_desc'] = 'Пересчёт статистики; может использоваться для исправления неверных данных.';
$txt['media_admin_maintenance_finderrors_desc'] = 'Попытка обнаружить наиболее распространённые ошибки: отсутствующий файл (в БД или физически) или неверный идентификатор последнего комментария/элемента.';
$txt['media_admin_maintenance_prune_desc'] = 'Очистка элементов/комментариев по определенным параметрам.';
$txt['media_admin_maintenance_browse_desc'] = 'Обзор файлов галереи и отображение использования дискового пространства каждым каталогом/файлом.';
$txt['media_admin_labels_modlog'] = 'Логи модерации';
$txt['media_admin_action_type'] = 'Тип действия';
$txt['media_admin_reported_item'] = 'Жалоба на элемент';
$txt['media_admin_reported_by'] = 'Сообщил';
$txt['media_admin_reported_on'] = 'Дата';
$txt['media_admin_del_report'] = 'Удалить жалобу';
$txt['media_admin_del_report_item'] = 'Удалить элемент';
$txt['media_admin_report_reason'] = 'Указана причина';
$txt['media_admin_banned_on'] = 'Дата выдачи бана';
$txt['media_admin_expires_on'] = 'Дата окончания бана';
$txt['media_never'] = 'Никогда';
$txt['media_admin_ban_type'] = 'Тип бана';
$txt['media_admin_ban_type_1'] = 'Полный';
$txt['media_admin_ban_type_2'] = 'Запрет на добавление элементов';
$txt['media_admin_ban_type_3'] = 'Запрет на добавление комментариев';
$txt['media_admin_ban_type_4'] = 'Запрет на добавление элементов и комментариев';
$txt['media_unapproved_items_notice'] = '<a href="%1$s">Элементов, ожидающих одобрения: %2$d</a>';
$txt['media_unapproved_coms_notice'] = '<a href="%1$s">Комментариев, ожидающих одобрения: %2$d</a>';
$txt['media_unapproved_albums_notice'] = '<a href="%1$s">Альбомов, ожидающих одобрения: %2$d</a>';
$txt['media_reported_items_notice'] = '<a href="%1$s">Жалоб на элементы: %2$d</a>';
$txt['media_reported_comments_notice'] = '<a href="%1$s">Жалоб на комментарии: %2$d</a>';
$txt['media_admin_modlog_approval_item'] = 'Одобрен элемент <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_ua_item'] = 'Отклонен элемент <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_item'] = 'Удален элемент %s (ожидал одобрения)';
$txt['media_admin_modlog_approval_com'] = 'Одобрен комментарий <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_com'] = 'Удален комментарий к элементу %s (ожидал одобрения)';
$txt['media_admin_modlog_approval_album'] = 'Одобрен альбом пользователя <a href="%s">%s</a>';
$txt['media_admin_modlog_approval_del_album'] = 'Удален альбом %s (ожидал одобрения)';
$txt['media_admin_modlog_delete_item'] = 'Удален элемент %s';
$txt['media_admin_modlog_delete_album'] = 'Удален альбом %s';
$txt['media_admin_modlog_delete_comment'] = 'Удален комментарий для элемента %s';
$txt['media_admin_modlog_delete_report_item_report'] = 'Удалена жалоба на элемент #%s';
$txt['media_admin_modlog_delete_report_comment_report'] = 'Удалена жалоба на комментарий #%s';
$txt['media_admin_modlog_delete_item_item_report'] = 'Удален элемент #%s по жалобе';
$txt['media_admin_modlog_delete_item_comment_report'] = 'Удален коментарий #%s по жалобе';
$txt['media_admin_modlog_ban_add'] = 'Забанен <a href="%s">%s</a>';
$txt['media_admin_modlog_ban_delete'] = 'Снят бан для <a href="%s">%s</a>';
$txt['media_admin_modlog_prune_item'] = 'Удалено устаревших элементов: %s';
$txt['media_admin_modlog_prune_comment'] = 'Удалено устаревших комментариев: %s';
$txt['media_admin_modlog_move'] = 'Элемент <a href=%s">%s</a> перемещен из альбома <a href="%s">%s</a> в альбом <a href="%s">%s</a>';
$txt['media_admin_modlog_qsearch'] = 'Быстрый поиск по пользователю';
$txt['media_admin_modlog_filter'] = 'Логи модерации для пользователя <a href="%s">%s</a>';
$txt['media_admin_view_image'] = 'Просмотр изображения';
$txt['media_admin_ftp_files'] = 'Файлы в каталоге FTP';
$txt['media_admin_profile_add'] = 'Добавить профиль';
$txt['media_admin_prof_name'] = 'Имя профиля';
$txt['media_admin_create_prof'] = 'Создать профиль';
$txt['media_admin_members'] = 'Пользователи';
$txt['media_admin_prof_del_switch'] = 'Переключение профилей';
$txt['media_quota_profile'] = 'Профиль квот для групп';
$txt['media_album_hidden'] = 'Скрыть альбом';
$txt['media_album_hidden_desc'] = 'Активируйте эту опцию, если хотите использовать этот альбом только в качестве контейнера для публикаций в блоге или на форуме.';
$txt['media_allowed_members'] = 'Белый список (чтение)';
$txt['media_allowed_members_desc'] = 'Укажите пользователей, которым нужно разрешить просматривать элементы альбома независимо от того, в какой группе они находятся.';
$txt['media_allowed_write'] = 'Белый список (запись)';
$txt['media_allowed_write_desc'] = 'Укажите пользователей, которым нужно разрешить загрузку в альбом независимо от того, в какой группе они находятся.';
$txt['media_denied_members'] = 'Чёрный список (чтение)';
$txt['media_denied_members_desc'] = 'Укажите пользователей, которым не слудет разрешать доступ к альбому независимо от того, в какой группе они находятся.';
$txt['media_denied_write'] = 'Чёрный список (запись)';
$txt['media_denied_write_desc'] = 'Укажите пользователей, которым не следует разрешать оставлять загрузку в альбом независимо от того, в какой группе они находятся.';
$txt['media_admin_wselected'] = 'Для выбранных';
$txt['media_admin_select_or'] = 'Или...';
$txt['media_admin_apply_perm'] = 'Добавить разрешение';
$txt['media_admin_clear_perm'] = 'Удалить разрешение';
$txt['media_admin_set_mg_perms'] = 'Установить права доступа как у этой группы';

// Admin error strings
$txt['media_admin_album_confirm'] = 'Хотите удалить этот альбом? Все элементы и комментарии внутри альбома также будут удалены.';
$txt['media_admin_name_left_empty'] = 'Название осталось незаполненным';
$txt['media_admin_invalid_target'] = 'Неверно указана цель';
$txt['media_admin_invalid_position'] = 'Неверно указана позиция';
$txt['media_admin_prune_invalid_days'] = 'Неверно указаны &quot;дни&quot;';
$txt['media_admin_no_albums'] = 'Нет альбомов';
$txt['media_admin_rm_selected'] = 'Удалить выбранные';
$txt['media_admin_rm_all'] = 'Удалить все';
$txt['media_report_not_found'] = 'Жалоб не найдено';
$txt['media_admin_bans_mems_empty'] = 'Не указан ник пользователя';
$txt['media_admin_bans_mems_not_found'] = 'Указанные пользователи не найдены';
$txt['media_ban_not_found'] = 'Банов не обнаружено';
$txt['media_admin_already_banned'] = 'Пользователь уже забанен!';
$txt['media_admin_unique_permission'] = 'Вы должны выбрать один из параметров';
$txt['media_admin_quick_none'] = 'Не выбраны параметры';
$txt['media_admin_invalid_groups'] = 'Была выбрана недействительная либо несуществующая группа.';

// Admin help strings
$txt['media_admin_desc'] = 'Админка медиатеки';
$txt['media_admin_settings_desc'] = 'Здесь расположены различные настройки медиатеки.';
$txt['media_admin_embed_desc'] = 'Здесь доступны настройки автовнедряемых элементов, включение/выключение автовнедрения внешних роликов (Youtube), просмотр и управление списками поддерживаемых сайтов.';
$txt['media_admin_albums_desc'] = 'Панель управления альбомами. Здесь можно добавлять, удалять и перемещать альбомы. Нажмите кнопку <strong>+</strong> для отображения дополнительной информации по альбому.';
$txt['media_admin_subs_desc'] = 'Панель управления элементами. Здесь можно одобрять, отклонять или удалять элементы, альбомы и комментарии.';
$txt['media_admin_maintenance_desc'] = 'Раздел обслуживания; содержит несколько полезных функций.';
$txt['media_admin_modlog_desc'] = 'Лог модерации. Здесь можно просмотреть журнал действий модераторов.';
$txt['media_admin_reports_desc'] = 'Панель управления жалобами. Здесь можно просмотреть жалобы, удалить их или удалить комментарии, элементы и альбомы, с ними связанные.';
$txt['media_admin_bans_desc'] = 'Панель управления банами. Здесь можно назначать, редактировать и отменять баны для пользователей медиатеки.';
$txt['media_admin_about_desc'] = 'Добро пожаловать в раздел администрирования медиатеки!';
$txt['media_admin_passwd_desc'] = 'Сообщите пароль пользователям, которым разрешен доступ в этот альбом. Оставьте поле пустым, если пароль не требуется.';
$txt['media_admin_maintenance_finderror_pending'] = 'Поиск продолжается. На данный момент обработано %s из %s элементов.<br><br><a href="%s">Нажмите для продолжения.</a> Подождите 1-2 секунды во избежание перегрузки сервера.';
$txt['media_admin_finderrors_1'] = 'Ошибки, обнаруженные в результате поиска';
$txt['media_admin_finderrors_missing_db_file'] = 'Ссылка в БД на оригинал файла #%s, для элемента #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_db_thumb'] ='Ссылка в БД на эскиз #%s, для элемента #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_db_preview'] ='Ссылка в БД на превью #%s, для элемента #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_physical_file'] = 'Оригинал файла #%s, для элемента #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_physical_thumb'] = 'Эскиз файла #%s, для элемента #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_physical_preview'] = 'Превью файла #%s, для элемента #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_album'] = 'Альбом #%s, связанный с элементом #<a href="%s">%s</a>, отсутствует.';
$txt['media_admin_finderrors_missing_last_comment'] = 'Комментарий #%s связан с отсутствующим элементом #<a href="%s">%s</a>.';
$txt['media_admin_finderrors_parent_album_access'] = 'Для удаления альбома #%s нужен доступ к родительскому альбому.';
$txt['media_admin_finderrors_done'] = 'Поиск ошибок завершен. Ошибок не обнаружено!';
$txt['media_admin_prune_done_items'] = 'Очистка устаревших элементов завершена! Удалено элементов: %s; комментариев: %s; файлов: %s';
$txt['media_admin_prune_done_comments'] = 'Очистка устаревших комментариев завершена! Удалено комментариев: %s';
$txt['media_admin_maintenance_prune_item_help'] = 'Удалить элементы старше &quot;x&quot; дней (значение задается ниже). Можно указать дополнительные параметры ниже, <b>но они не обязательны</b>. Операцию можно применить ко всем или только к выбранным альбомам.';
$txt['media_admin_maintenance_prune_com_help'] = 'Удалить комментарии старше &quot;x&quot; дней (значение задается ниже). Операцию можно применить для всех или выбранных альбомов.';
$txt['media_admin_maintenance_checkfiles_done'] = 'Неиспользуемые файлы были удалены. Всего удалено %s файлов, освобождено %s КБ дискового пространства.';
$txt['media_admin_maintenance_checkfiles_no_files'] = 'Неиспользуемых файлов не обнаружено';
$txt['media_admin_maintenance_checkfiles_found'] = 'Обнаружено %s не использующихся файлов общим объемом %s КБ. <a href="%s">Нажмите здесь</a> для их удаления.';
$txt['media_admin_maintenance_checkorphans_done'] = 'Все ненужные файлы были удалены; в количестве %s штук:';
$txt['media_admin_maintenance_checkorphans_no_files'] = 'Не обнаружено ненужных файлов';
$txt['media_admin_maintenance_clear_pending'] = 'Скрипт всё ещё работает. Обработано %s из %s элементов.<br><br>Пожалуйста, <a href="%s">нажмите здесь</a> для продолжения. Подождите 1-2 секунды во избежание перегрузки сервера.';
$txt['media_admin_maintenance_clear_done'] = 'Все файлы успешно переименованы.';
$txt['media_admin_installed_on'] = 'Дата установки';
$txt['media_admin_icon_edit_desc'] = 'Если укажете новую обложку, старая будет перезаписана. Оставьте поле пустым, чтобы сохранить старую обложку.';
$txt['media_admin_bans_mems_empty'] = 'Не указано имя пользователя';
$txt['media_admin_expires_on_help'] = 'Укажите, через сколько дней бан будет снят';
$txt['media_admin_modlog_desc'] = 'Это лог модерации. Здесь можно почитать журнал действий модераторов. Помните, что удаленные логи уничтожаются навсегда.';
$txt['media_admin_ftp_desc'] = 'Импорт элементов в медиатеку из удалённой папки на сервере. Это может быть полезно для загрузки очень больших файлов, которые PHP не будет принимать в процессе обычной загрузки.';
$txt['media_admin_ftp_help'] = 'Это список файлов в каталоге {Data_dir}/ftp на сервере. Пожалуйста, выберите альбом для добавления в него этих файлов.';
$txt['media_admin_ftp_halted'] = 'Во избежание перегрузки сервера скрипт приостановит свою работу. На данный момент обработано %s из %s элементов. Импорт будет продолжен автоматически.';
$txt['media_admin_perms_desc'] = 'Здесь можно настроить несколько разных профилей, контролирующих доступ пользователей к альбомам и элементам.';
$txt['media_admin_prof_del_switch_help'] = 'Если хотите удалить профиль, используемый сейчас, то сначала переключитесь на другой.';
$txt['media_admin_quotas_desc'] = 'Здесь можно управлять ограничениями для разных групп пользователей.';
$txt['media_admin_perms_warning'] = '<strong>Предупреждение</strong>: эта страница только для установки прав доступа к альбомам. Общие настройки прав доступа для медиатеки изменяются в <a href="%s">панели администрирования</a> Wedge.';

// Per-album Permissions
$txt['permissionname_media_download_item'] = 'Скачивание элементов';
$txt['permissionname_media_add_videos'] = 'Добавление видеофайлов';
$txt['permissionname_media_add_audios'] = 'Добавление аудиофайлов';
$txt['permissionname_media_add_docs'] = 'Добавление документов';
$txt['permissionname_media_add_embeds'] = 'Добавление внедряемых элементов';
$txt['permissionname_media_add_images'] = 'Добавление изображений';
$txt['permissionname_media_rate_items'] = 'Оценивание элементов';
$txt['permissionname_media_edit_own_com'] = 'Редактирование собственных комментариев';
$txt['permissionname_media_report_com'] = 'Жалобы на комментарии';
$txt['permissionname_media_edit_own_item'] = 'Редактирование собственных элементов';
$txt['permissionname_media_comment'] = 'Комментирование элементов';
$txt['permissionname_media_report_item'] = 'Жалобы на элементы';
$txt['permissionname_media_auto_approve_com'] = 'Автоодобрение комментариев';
$txt['permissionname_media_auto_approve_item'] = 'Автоодобрение элементов';
$txt['permissionname_media_multi_upload'] = 'Мультизагрузка';
$txt['permissionname_media_whoratedwhat'] = 'Просмотр, кто и как оценил элемент';
$txt['permissionname_media_multi_download'] = 'Скачивание одним файлом';

// Custom fields
$txt['media_cf_invalid'] = 'Указанное значение для %s неверно';
$txt['media_cf_empty'] = 'Поле %s не заполнено';
$txt['media_cf_bbc'] = 'Можно использовать ББ-теги';
$txt['media_cf_required'] = 'Это обязательное поле';
$txt['media_cf_desc'] = 'Здесь можно управлять дополнительными полями для альбомов';
$txt['media_admin_labels_fields'] = 'Дополнительные поля';
$txt['media_cf_name'] = 'Наименование';
$txt['media_cf_type'] = 'Тип';
$txt['media_cf_req'] = 'Обязательное';
$txt['media_cf_searchable'] = 'Значение поля участвует в поиске';
$txt['media_cf_bbcode'] = 'ББ-код';
$txt['media_cf_editing'] = 'Добавление/редактирование дополнительного поля';
$txt['media_cf_text'] = 'Строка';
$txt['media_cf_radio'] = 'Переключатель';
$txt['media_cf_checkbox'] = 'Флажок';
$txt['media_cf_textbox'] = 'Текст';
$txt['media_cf_select'] = 'Список выбора';
$txt['media_cf_options'] = 'Параметры поля';
$txt['media_cf_options_desc'] = 'Укажите параметры для полей типа &laquo;Флажок&raquo;, &laquo;Переключатель&raquo; или &laquo;Список выбора&raquo;. Используйте запятую (,) как разделитель';
