<?php
// Version: 2.0; ManageMaintenance

$txt['fix_board_urls'] = 'Найдены разделы с некорректной длиной ЧПУ.';
$txt['repair_zero_ids'] = 'Найти темы и/или сообщения, ID которых равен 0.';
$txt['repair_missing_topics'] = 'Сообщение #%1$d в несуществующей теме #%2$d.';
$txt['repair_missing_messages'] = 'Тема #%1$d не содержит фактических сообщений.';
$txt['repair_stats_topics_1'] = 'Тема #%1$d содержит первое сообщение с некорректным ID %2$d.';
$txt['repair_stats_topics_2'] = 'Тема #%1$d содержит последнее сообщение с некорректным ID %2$d.';
$txt['repair_stats_topics_3'] = 'Тема #%1$d содержит неправильное количество ответов: %2$d.';
$txt['repair_stats_topics_4'] = 'Тема #%1$d содержит неправильное количество неодобренных сообщений: %2$d.';
$txt['repair_stats_topics_5'] = 'Тема #%1$d содержит неправильное значение одобрения.';
$txt['repair_missing_boards'] = 'Тема #%1$d на форуме #%2$d не существует.';
$txt['repair_missing_categories'] = 'Раздел #%1$d в категории #%2$d не существует.';
$txt['repair_missing_posters'] = 'Сообщение #%1$d, отправленное пользователем #%2$d, не существует.';
$txt['repair_missing_parents'] = 'В разделе #%1$d не существует подраздела #%2$d.';
$txt['repair_missing_polls'] = 'В теме #%1$d не найдено голосования #%2$d.';
$txt['repair_polls_missing_topics'] = 'Голосование #%1$d связано с несуществующей темой #%2$d.';
$txt['repair_missing_log_topics'] = 'Тема #%1$d, отмеченная как прочитанная одним или более пользователем, отсутствует.';
$txt['repair_missing_log_topics_members'] = 'Пользователь #%1$d отметил одну или более тему как прочитанную, но она отсутствует.';
$txt['repair_missing_log_mark_read'] = 'Раздел #%1$d, отмеченный прочитанным одним или более пользователями, не существует.';
$txt['repair_missing_log_mark_read_members'] = 'Пользователь #%1$d, отметивший один или более разделов прочитанными, не существует.';
$txt['repair_missing_pms'] = 'Личное сообщение #%1$d, отосланное одному или более пользователям, не существует.';
$txt['repair_missing_recipients'] = 'Пользователь #%1$d, получивший одно или более личных сообщений, не существует.';
$txt['repair_missing_senders'] = 'Личное сообщение #%1$d, отосланное пользователем #%2$d, не существует.';
$txt['repair_missing_notify_members'] = 'Объекты уведомления, отмеченные пользователем #%2$d, не существуют.';
$txt['repair_missing_cached_subject'] = 'Название темы #%1$d не было сохранено.';
$txt['repair_missing_topic_for_cache'] = 'Словоформы \'%1$d\' ссылаются на несуществующую тему.';
$txt['repair_missing_log_poll_member'] = 'Голосование #%1$d было открыто пользователем #%2$d, который сейчас не существует.';
$txt['repair_missing_log_poll_vote'] = 'Пользователем был отдан голос #%1$d в несуществующем голосовании #%2$d.';
$txt['repair_missing_thumbnail_parent'] = 'Существует эскиз картинки с именем %1$s, но нет самой картинки.';
$txt['repair_report_missing_comments'] = 'Отчёт #%1$d о теме: &quot;%s&quot; не содержит комментариев.';
$txt['repair_comments_missing_report'] = 'Комментарий к отчёту #%1$d от %s не связан ни с одним отчётом.';
$txt['repair_group_request_missing_member'] = 'Запрос на членство в группе существует для удаленного пользователя #%1$d.';
$txt['repair_group_request_missing_group'] = 'Запрос на членство в группе существует для удаленной группы #%1$d.';

$txt['repair_currently_checking'] = 'Проверить: &quot;%1$s&quot;';
$txt['repair_currently_fixing'] = 'Исправить: &quot;%1$s&quot;';
$txt['repair_operation_zero_topics'] = 'Темы с id_topic, некорректно установленным в 0';
$txt['repair_operation_zero_messages'] = 'Сообщения с id_msg, некорректно установленным в 0';
$txt['repair_operation_missing_topics'] = 'Сообщения принадлежат несуществующей теме';
$txt['repair_operation_missing_messages'] = 'Темы без сообщений';
$txt['repair_operation_stats_topics'] = 'Темы с некорректными первым или последним сообщением';
$txt['repair_operation_stats_topics2'] = 'Темы с неверным количеством ответов в них';
$txt['repair_operation_stats_topics3'] = 'Темы с неверным количеством неодобренных сообщений';
$txt['repair_operation_missing_boards'] = 'Темы принадлежат отсутствующему разделу';
$txt['repair_operation_missing_categories'] = 'Разделы принадлежат несуществующей категории';
$txt['repair_operation_missing_posters'] = 'Сообщения привязаны к несуществующим пользователям';
$txt['repair_operation_missing_parents'] = 'Дочерние разделы не имеют родителей';
$txt['repair_operation_missing_polls'] = 'Темы привязаны к несуществующим голосованиям';
$txt['repair_operation_missing_log_topics'] = 'Логи привязаны к несуществующим темам';
$txt['repair_operation_missing_log_topics_members'] = 'Логи привязаны к несуществующим пользователям';
$txt['repair_operation_missing_log_mark_read'] = 'Отметка прочтения привязана к несуществующим разделам';
$txt['repair_operation_missing_log_mark_read_members'] = 'Отметка прочтения привязана к несуществующим пользователям';
$txt['repair_operation_missing_pms'] = 'Отправитель личного сообщения отсутствует';
$txt['repair_operation_missing_recipients'] = 'Отправитель личного сообщения ссылается на несуществующего пользователя';
$txt['repair_operation_missing_senders'] = 'Личные сообщения привязаны к несуществующему пользователю';
$txt['repair_operation_missing_notify_members'] = 'Логи уведомлений ссылаются на несуществующего пользователя';
$txt['repair_operation_missing_cached_subject'] = 'Темы отсутствуют в поисковом кэше';
$txt['repair_operation_missing_topic_for_cache'] = 'Кэш поиска ссылается на несуществующую тему';
$txt['repair_operation_missing_member_vote'] = 'Результаты голосования привязаны к несуществующим пользователям';
$txt['repair_operation_missing_log_poll_vote'] = 'Результаты голосования привязаны к несуществующему опросу';
$txt['repair_operation_report_missing_comments'] = 'Отчёты о теме без комментария';
$txt['repair_operation_comments_missing_report'] = 'Комментарии к отчёту не связан ни с одним отчётом';
$txt['repair_operation_group_request_missing_member'] = 'Запросы на участие в группе от несуществующего пользователя';
$txt['repair_operation_group_request_missing_group'] = 'Запросы на участие в несуществующей группе';

$txt['salvaged_category_name'] = 'Восстановленные данные';
$txt['salvaged_category_error'] = 'Невозможно создать категорию "Восстановленные данные"!';
$txt['salvaged_board_name'] = 'Восстановленные темы';
$txt['salvaged_board_description'] = 'Темы, созданные для сообщений из несуществующих тем';
$txt['salvaged_board_error'] = 'Невозможно создать раздел "Восстановленные темы"!';
$txt['salvaged_poll_topic_name'] = 'Восстановленное голосование';
$txt['salvaged_poll_message_body'] = 'Это голосование не было связано ни с какой темой.';

$txt['database_optimize'] = 'Оптимизировать базу данных';
$txt['database_numb_tables'] = 'Ваша база данных содержит %1$d таблиц.';
$txt['database_optimize_attempt'] = 'Попытка оптимизировать базу данных...';
$txt['database_optimizing'] = 'Оптимизация %1$s... %2$f кб оптимизировано.';
$txt['database_optimized'] = array(0 => 'Все таблицы были оптимизированы.', 1 => '%1$d таблица оптимизирована.', 'n' => '%1$d таблиц оптимизировано.');
$txt['database_no_id'] = 'такого ID пользователя не существует';

// Error and intrusion logs.
$txt['apply_filter'] = 'Применить фильтр';
$txt['applying_filter'] = 'Применяется фильтр';
$txt['filter_only_member'] = 'Показать сообщения об ошибках этого пользователя';
$txt['filter_only_ip'] = 'Показать сообщения об ошибках этого IP адреса';
$txt['filter_only_url'] = 'Показать сообщения об ошибках этого URL-адреса';
$txt['filter_only_message'] = 'Показать ошибки только с такими же сообщениями';
$txt['filter_only_ua'] = 'Показать ошибки только с таким же пользовательским агентом (user agent)';
$txt['error_url'] = 'URL-адрес страницы, вызывающей ошибку';
$txt['error_message'] = 'Сообщение об ошибке';
$txt['clear_filter'] = 'Очистить фильтр';
$txt['remove_selection'] = 'Удалить выделенное';
$txt['remove_filtered_results'] = 'Удалить все результаты фильтрации';
$txt['sure_about_errorlog_remove'] = 'Хотите удалить все сообщения об ошибках?';
$txt['reverse_direction'] = 'Показать в обратном хронологическом порядке';
$txt['error_type'] = 'Тип ошибки';
$txt['filter_only_type'] = 'Отображать ошибки только этого типа';
$txt['filter_only_file'] = 'Отображать ошибки только этого файла';
$txt['apply_filter_of_type'] = 'Применить фильтр';
$txt['request_method'] = 'Метод запроса';
$txt['request_protocol'] = 'Протокол запроса';
$txt['user_agent'] = 'User agent';
$txt['http_headers'] = 'Другие заголовки HTTP:';
$txt['file_out_of_bounds'] = 'Этот файл короче указанного номера строки, поэтому он не может быть показан. Может быть, вы изменили его?';

$txt['errortype_all'] = 'Все ошибки';
$txt['errortype_general'] = 'Общие';
$txt['errortype_general_desc'] = 'Общие ошибки, которые не были отнесены к другим типам';
$txt['errortype_critical'] = '<span style="color:red;">Критические</span>';
$txt['errortype_critical_desc'] = 'Критические ошибки. Их желательно исправить как можно быстрее. Наличие таких ошибок может вызвать некорректную работу форума и стать причиной нарушения безопасности работы.';
$txt['errortype_database'] = 'База данных';
$txt['errortype_database_desc'] = 'Ошибки, вызванные некорректными запросами. Должны быть рассмотрены и отправлены команде Wedge.';
$txt['errortype_undefined_vars'] = 'Неопределенные';
$txt['errortype_undefined_vars_desc'] = 'Ошибки, вызванные неправильной передачей параметров или их отсутствием.';
$txt['errortype_mail'] = 'Почта';
$txt['errortype_mail_desc'] = 'Ошибки, возникающие при отправке электропочты. Большое количество ошибок может указывать на неправильные настройки.';
$txt['errortype_filenotfound'] = 'Файл не найден';
$txt['errortype_filenotfound_desc'] = 'Ошибки, вызванные запросами к файлам, отсутствующим на сервере.';
$txt['errortype_template'] = 'Шаблон';
$txt['errortype_template_desc'] = 'Ошибки, вызванные загрузкой шаблонов.';
$txt['errortype_password'] = 'Пароли';
$txt['errortype_password_desc'] = 'Пользователи, которые ввели неправильный пароль.';
$txt['errortype_user'] = 'Пользователь';
$txt['errortype_user_desc'] = 'Ошибки, вызванные пользователем. Включают неправильный ввод пароля, попытки входа при наличии бана, а также попытки доступа в различные разделы форума без соответствующих прав.';

$txt['maintain_recount'] = 'Пересчитать статистику по всем разделам';
$txt['maintain_recount_info'] = 'Пересчитывает количество тем и разделов, сообщений в них, количество писем в личных ящиках и т. п.';
$txt['maintain_errors'] = 'Найти и исправить любые ошибки';
$txt['maintain_errors_info'] = 'Если, к примеру, сообщения или темы отсутствуют после падения сервера, эта функция сможет помочь восстановить потерянные данные.';
$txt['maintain_logs'] = 'Удалить незначительные логи';
$txt['maintain_logs_info'] = 'Очищает ненужные логи, которые больше не нужны.';
$txt['maintain_cache'] = 'Очистить файл кэша';
$txt['maintain_cache_info'] = 'Используется для очистки кэша при модификации файлов форума или языковых строк, когда требуется чтобы форум «забыл» старые данные.';
$txt['maintain_optimize'] = 'Оптимизировать все таблицы.';
$txt['maintain_optimize_info'] = 'Эта функция используется для увеличения быстродействия форума, т. к. уничтожает все индексы таблиц и создает их заново на основании данных, находящихся в таблицах БД.';
$txt['maintain_version'] = 'Проверить версии используемых файлов';
$txt['maintain_version_info'] = 'Эта функция дает возможность сравнения текущих версий файлов движка форума с версиями, имеющимися у разработчика движка.';
$txt['maintain_run_now'] = 'Начать выполнение';
$txt['maintain_return'] = 'Вернутся в обслуживание форума';

$txt['maintain_old'] = 'Удалить старые сообщения';
$txt['maintain_old_since'] = 'Удалить все темы, в которых не было новых сообщений в течение %1$s дней:';
$txt['maintain_old_move_since'] = 'Переместить все темы, в которых не было новых сообщений в течение %1$s дней:';
$txt['maintain_old_nothing_else'] = 'Любой тип темы.';
$txt['maintain_old_are_moved'] = 'Уведомления о перемещении тем.';
$txt['maintain_old_are_locked'] = 'Закрытые темы.';
$txt['maintain_old_are_not_pinned'] = 'Не удалять прикрепленные темы.';
$txt['maintain_old_all'] = 'Все разделы (нажмите для выбора определенных)';
$txt['maintain_old_choose'] = 'Выбранные разделы (нажмите для выбора всех)';
$txt['maintain_old_remove'] = 'Удалить';
$txt['maintain_old_confirm'] = 'Хотите удалить старые сообщения?<br><br>Это не может быть отменено!';

$txt['maintain_members'] = 'Удалить неактивных пользователей';
$txt['maintain_members_ungrouped'] = 'Пользователи без групп <span class="smalltext">(Пользователи, не относящиеся ни к одной из групп)</span>';
$txt['maintain_members_since1'] = 'Удалить всех пользователей, которые не';
$txt['maintain_members_since2'] = 'в течение';
$txt['maintain_members_since3'] = ' дней.';
$txt['maintain_members_activated'] = 'активировали свои учётные записи';
$txt['maintain_members_logged_in'] = 'посещали форум';
$txt['maintain_members_all'] = 'Все группы пользователей';
$txt['maintain_members_choose'] = 'Выбранные группы';
$txt['maintain_members_confirm'] = 'Хотите удалить учётную запись данного пользователя?<br><br>Это действие нельзя будет отменить!';

$txt['maintain_recountposts'] = 'Пересчитать сообщения пользователей';
$txt['maintain_recountposts_desc'] = 'Эта функция пересчитает количество сообщений всех пользователей форума, для правильного применения разрешений, основанных на количестве сообщений.';

// Move topics out.
$txt['move_topics_maintenance'] = 'Перенос тем';
$txt['move_topics_select_board'] = 'Выбрать раздел';
$txt['move_topics_from'] = 'Перенести темы из';
$txt['move_topics_to'] = 'в';
$txt['move_topics_now'] = 'Перенести';
$txt['move_topics_confirm'] = 'Хотите перенести ВСЕ темы из раздела &quot;%board_from%&quot; в раздел &quot;%board_to%&quot;?';

$txt['maintain_reattribute_posts'] = 'Присвоить сообщения пользователю';
$txt['reattribute_guest_posts'] = 'Найти все сообщения гостя, опубликованные';
$txt['reattribute_email'] = 'Под электропочтой:';
$txt['reattribute_username'] = 'Или под указанным логином:';
$txt['reattribute_user'] = 'И объединить с пользователем:';
$txt['reattribute_current_member'] = '... и присвоить их пользователю';
$txt['reattribute_increase_posts'] = 'Добавить количество сообщений пользователю';
$txt['reattribute'] = 'Присвоить';
$txt['reattribute_confirm'] = 'Хотите присвоить все сообщения гостей с %type% "%find%" пользователю "%member_to%"?';
$txt['reattribute_confirm_merge'] = 'Хотите объединить все сообщения учётной записи "%find%" с пользователем "%member_to%"?';
$txt['reattribute_confirm_username'] = 'имя пользователя';
$txt['reattribute_confirm_email'] = 'электропочта';
$txt['reattribute_cannot_find_member'] = 'Не удалось найти пользователя, которому нужно присвоить сообщения.';
$txt['reattribute_cannot_find_member_from'] = 'Не удалось найти пользователя для объединения.';
